### ISSUE TITLE
Problema anime 

### ISSUE THREAD

**Issue by berta24** [MainKronos/Sonarr-AnimeDownloader#1]
Ciao, ho un problema, volevo usare il tuo fantastico programma per scaricarmi One piece, su animeworld è composto da una parte in italiano e una in jap subita, a me interessava solo la parte in jap, quindi dal 579 in poi, ovvero dalla 16 in poi di sonarr, ma se nella table metto che la stagione 16 si chiama One Piece invece di One Piece (ITA) mi dice che l’anime deve ancora uscire.
Ho provato un po’ tutte le alternative, a specificare ogni stagione, a partire solo dalla 1 o solo dalla 16 ma nada... Help pls
![4AF69889-5B88-402A-B29F-FC2BA8DEC435](https://user-images.githubusercontent.com/25983005/103059258-dd9dee00-45a4-11eb-9608-54c2c9f7f629.png)
![B0AFEB31-A3E6-4DDA-B94A-0199F579E579](https://user-images.githubusercontent.com/25983005/103059262-e0004800-45a4-11eb-8f82-f183dcfd593a.jpeg)

**Comment by MainKronos** [comment]
ok, grazie per la tua segnalazione, Cerco di capire qual'è il problema

**Comment by MainKronos** [comment]
@berta24 Il problema 'dovrebbe' essere risolto nella versione `0.3.0`. Quando passerai alla versione `0.3.0` assicurati di convertire il file `table.json`. L'ho dovuto modificare per rimuover la ridondanza delle informazioni che si sarebbero poi create con questo aggiornamento.

Visto che non sono completamente sicuro di aver gestito questo errore per condizioni limite, lo manterò aperto per un po'.... 

_è stata davvero una faticaccia... ahahahhaah_

**Comment by berta24** [comment]
ahahah immagino... Ottimo allora aspetterò con ansia la 3.0 e in caso ti farò da cavia, senti un altra informazione, non so se devo aprire un altro Issue oppure posso scrivere qui, praticamente indipendentemente dalla cartella che seleziono, gli anime me li salva sempre e solo in /script, sbaglio qualcosa io?
