### ISSUE TITLE
[BUG] Errore spostamento file con volume /downloads creato

### ISSUE THREAD

**Issue by BroHPotato** [MainKronos/Sonarr-AnimeDownloader#101]
### Livello di Errore:
- `🅴🆁🆁🅾🆁`

### Descrizione 
con il volume per il download settato lo spostamento avviene nel path /downloads e non in /tv
questo è il mapping dei volumi

AnimeDownloader
![immagine](https://github.com/MainKronos/Sonarr-AnimeDownloader/assets/35737374/10d23cb4-8845-4d89-a371-5f35a1dc1aeb)
Sonarr
![immagine](https://github.com/MainKronos/Sonarr-AnimeDownloader/assets/35737374/880b60ef-bf7d-462d-9993-4e3ad6369433)
 il path è uguale, mi aspettavo che facesse il download in /downloads e spostasse in /tv/path/di/sonnar ora sposta in /downloads/path/di/sonarr

Log sostiene di aver spostato
![immagine](https://github.com/MainKronos/Sonarr-AnimeDownloader/assets/35737374/29f874d0-9758-4365-9923-983c101a20ad)

**Comment by MainKronos** [comment]
Mi puoi inviare anche il file docker-compose o il comando docker run che usi?

**Comment by BroHPotato** [comment]
docker run -d \
    --name=anime-downloader \
    -v /home/maverick/Documenti/anime-downloader:/script/json/ \
    -v /mnt/md0/Media:/tv \
    -v /mnt/md0/Download:/downloads \
    -v /home/maverick/Documenti/anime-downloader/Connections:/script/connections \
    -p 5000:5000 \
    --env SONARR_URL='http://192.168.188.2:8989' \
    --env API_KEY='********' \
    --env TZ=Europe/Rome \
    --env PUID=1000 \
    --env PGID=1000 \
    ghcr.io/mainkronos/anime_downloader:latest

ovvio workaround testato è mettere i volimi che puntano nella stessa cartella
    -v /mnt/md0/Media:/tv \
    -v /mnt/md0/Media:/downloads

**Comment by MainKronos** [comment]
mi fai vedere anche quello di Sonarr, forse ho capito qual è il problema

**Comment by BroHPotato** [comment]
docker run -d   --name=sonarr   -e PUID=1000   -e PGID=1000   -e TZ=Etc/UTC   -p 8989:8989   -v /home/maverick/Documenti/sonarr:/config   -v /mnt/md0/Media:/tv    -v /mnt/md0/Media:/downloads    --restart unless-stopped   lscr.io/linuxserver/sonarr:latest

**Comment by MainKronos** [comment]
mhhh, strano....
Mi puoi dire cosa ti restituisce questa chiamata GET: `http://192.168.188.2:8989/api/wanted/missing?apikey={API_KEY}&sortKey=airDateUtc&page=1`

Sostituisci `{API_KEY}` con l'api_key di sonarr

**Comment by BroHPotato** [comment]
ook, scoperto l'arcano, grazie per il supporto! L'import dei titoli è stato fatto in sodar dalla cartella /downloads e non dalla cartella /tv questo quindi ritorna il path /downloads/serire/stagione, devo reimportare da /tv! user error, scusami e grazie ancora per il supporto!
