### ISSUE TITLE
[BUG] DeprecatedLibrary

### ISSUE THREAD

**Issue by MainKronos** [MainKronos/Sonarr-AnimeDownloader#102]
### Livello di Errore:
- `🅰🅻🅴🆁🆃`

### Messaggi di Errore
- 🅰🅻🅴🆁🆃: Il sito è cambiato, di conseguenza la libreria è DEPRECATA. -> [File /usr/local/lib/python3.9/site-packages/animeworld/utility.py in fixCookie - 42]

- ⚠️ Errore di connessione. (('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))

### Descrizione
Il sito animeworld è cambiato e la libreria non riesce piú a funzionare correttamente.\
In questo caso possono essere sollevati 2 diversi errori, quello classico di alert che segnale cha la libreria è deprecata e un errore di connessione, entrambi sono causati dallo stesso problema.

**Comment by MainKronos** [comment]
Libreria [AnimeWorld-API](https://github.com/MainKronos/AnimeWorld-API) in aggiornamento...

**Comment by MainKronos** [comment]
Libreria [AnimeWorld-API](https://github.com/MainKronos/AnimeWorld-API) aggiornata alla versione [1.6.0](https://github.com/MainKronos/AnimeWorld-API/releases/tag/v1.6.0).

Come sempre riavviate il container o ricreatelo per scaricare gli aggiornamenti. 👍

**Comment by r0bb10** [comment]
> Libreria [AnimeWorld-API](https://github.com/MainKronos/AnimeWorld-API) aggiornata alla versione [1.6.0](https://github.com/MainKronos/AnimeWorld-API/releases/tag/v1.6.0).
> 
> Come sempre riavviate il container o ricreatelo per scaricare gli aggiornamenti. 👍

Volevo proprio aprire un ticket ieri sera, confermo che è tornato a funzionare, grande come sempre 👍

**Comment by MainKronos** [comment]
🅰🅻🅴🆁🆃: Il sito è cambiato, di conseguenza la libreria è DEPRECATA. -> [File /usr/local/lib/python3.9/site-packages/animeworld/utility.py in fixCookie - 31]


sti stanno dando da fare quelli di animeworld...

**Comment by MainKronos** [comment]
Risolto con la versione [1.6.1](https://github.com/MainKronos/AnimeWorld-API/releases/tag/v1.6.1) della libreria [animeworld](https://github.com/MainKronos/AnimeWorld-API)
