### ISSUE TITLE
[BUG] Invalid type for url.

### ISSUE THREAD

**Issue by Simoneu01** [MainKronos/Sonarr-AnimeDownloader#103]
### Livello di Errore:
- `🅴🆁🆁🅾🆁`

### Messaggio di Errore
```
🅴🆁🆁🅾🆁: Invalid type for url.  Expected str or httpx.URL, got <class 'NoneType'>: None
Traceback (most recent call last):
  File "/script/job.py", line 74, in job
    file = ep.download(title, DOWNLOAD_FOLDER, hook=fun.downloadProgress, opt=opt)
  File "/usr/local/lib/python3.9/site-packages/animeworld/episodio.py", line 123, in download
    return self.__choiceBestServer().download(title,folder,hook=hook,opt=opt)
  File "/usr/local/lib/python3.9/site-packages/animeworld/episodio.py", line 179, in __choiceBestServer
    with SES.stream("GET", test["server"].fileLink(), timeout=0.9, follow_redirects=True) as r:
  File "/usr/local/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 844, in stream
    request = self.build_request(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 346, in build_request
    url = self._merge_url(url)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 376, in _merge_url
    merge_url = URL(url)
  File "/usr/local/lib/python3.9/site-packages/httpx/_urls.py", line 117, in __init__
    raise TypeError(
TypeError: Invalid type for url.  Expected str or httpx.URL, got <class 'NoneType'>: None
```

### Descrizione [_Opzionale_]
> _Inserire qui una breve descrizione del problema._

**Comment by MainKronos** [comment]
Quando accade? Per il download di un episodio specifico? O mentre controlla se è uscito un episodio?
Mi puoi allegare il file di log

**Comment by Simoneu01** [comment]
> Quando accade? Per il download di un episodio specifico? O mentre controlla se è uscito un episodio? Mi puoi allegare il file di log

Mentre scarica (penso)

File:
[log.log](https://github.com/MainKronos/Sonarr-AnimeDownloader/files/11840374/log.log)

**Comment by MainKronos** [comment]
Ho capito il problema. Ho fatto dei test e a quanto pare quell'anime, essendo abbastanza vecchio, gli hanno rimosso il file dai server di streamtape ma hanno lasciato intatto il link sul sito di animeworld. Quindi quando la libreria prova a scaricare il file esplode tutto.
Cerco di sistemare quanto prima

**Comment by MainKronos** [comment]
Come soluzione temporanea non scaricare gli episodi di quella serie 😂 (deselezionali da sonarr).
Così tutto il resto dovrebbe funzionare

**Comment by Simoneu01** [comment]
> Come soluzione temporanea non scaricare gli episodi di quella serie 😂 (deselezionali da sonarr). Così tutto il resto dovrebbe funzionare

ok ok ,quindi non scarica dal server di animeworld? solo streamtape?

**Comment by Simoneu01** [comment]
Un attimo, l'errore me lo da con l'episodio 51, e c'è anche da streamtape :
https://www.animeworld.so/play/digimon-adventure-ita.42Pgn/XUCF-

![image](https://github.com/MainKronos/Sonarr-AnimeDownloader/assets/43807696/c344861e-092a-4bc4-9dbd-634a8ba3b8fa)

**Comment by MainKronos** [comment]
> > Come soluzione temporanea non scaricare gli episodi di quella serie 😂 (deselezionali da sonarr). Così tutto il resto dovrebbe funzionare
> 
> ok ok ,quindi non scarica dal server di animeworld? solo streamtape?

Ad essere precisi l'episodio viene scaricato da uno dei server supportati. Per scegliere il server prova a vedere la velocità di download di tutti i server disponibili. Se un link non è valido è qui che esplode

**Comment by MainKronos** [comment]
> Un attimo, l'errore me lo da con l'episodio 51, e c'è anche da streamtape : https://www.animeworld.so/play/digimon-adventure-ita.42Pgn/XUCF-
> 
> ![image](https://user-images.githubusercontent.com/43807696/248066229-c344861e-092a-4bc4-9dbd-634a8ba3b8fa.png)

Quel pulsante manda ad una pagina insesistente: https://streamtape.com/v/doBaQBGAm2ikWZr/DigimonAdventure_Ep_51_ITA.mp4

**Comment by MainKronos** [comment]
Risolto con la versione [1.6.1](https://github.com/MainKronos/AnimeWorld-API/releases/tag/v1.6.1) della libreria [animeworld](https://github.com/MainKronos/AnimeWorld-API)
