### ISSUE TITLE
[BUG] Deprecated Library

### ISSUE THREAD

**Issue by devaleriofrancesco** [MainKronos/Sonarr-AnimeDownloader#106]
### Livello di Errore:
- `🅰🅻🅴🆁🆃`

### Messaggio di Errore
Il sito è cambiato, di conseguenza la libreria è DEPRECATA. -> [File /usr/local/lib/python3.9/site-packages/animeworld/anime.py in getName - 190

**Comment by MainKronos** [comment]
Hai sempre questo errore? L'ho notato anche io, ma c'è stato solo verso le 23:00 di ieri. Probabilmente facevano manutenzione al sito.

Se hai sempre questo errore dimmi a che anime si blocca che ci do un'occhiata

**Comment by devaleriofrancesco** [comment]
Ciao,

Ora funziona correttamente, segnalo come risolto. Grazie mille.
