### ISSUE TITLE
[QUESTION] No connection adapters were found

### ISSUE THREAD

**Issue by JacopoBassan** [MainKronos/Sonarr-AnimeDownloader#107]
### Descrizione
> Dopo aver configurato Sonarr e AnimeDownloader sono arrivato ad un ultimo scoglio che non mi è chiaro ne trovo nelle FAQ o altro, ovvero l'errore nei log di AnimeDownloader
`⚠️ Errore di connessione. (No connection adapters were found for '192.168.0.2:8989/api/tag?apikey=*APYKEY*')`
L'IP è corretto, la porta anche, l'api key idem, se provo a controllare quell'url mi risponde con un array vuoto.
Ad una certa pensavo di aver trovato la soluzione, avevo dovuto reinstallare sonarr e mi ero dimenticato di cambiare l'apikey con la nuova e infatti l'url mi dava errore di autenticazione, ma ora non capisco cosa manchi.

### Conferma di presa visione
- [x] Confermo di aver controllato la sezione [FAQ](https://github.com/MainKronos/Sonarr-AnimeDownloader/blob/main/FAQ.md) e di non aver trovato nessuna soluzione al problema.
- [x] Confermo di aver controllato tra gli [Issue](https://github.com/MainKronos/Sonarr-AnimeDownloader/issues?q=is%3Aissue+label%3A%22help+wanted%22%2Cquestion%2Cdocumentation+-label%3A%22fixed+on+dev%22) e di non aver trovato nessuna soluzione al problema.

**Comment by JacopoBassan** [comment]
@MainKronos certo, anche se non c'è molto di più, se posso recuperare altro dimmi pure [log.log](https://github.com/MainKronos/Sonarr-AnimeDownloader/files/12192567/log.log)

**Comment by MainKronos** [comment]
Probabilmente hai scritto male il valore della variabile d'ambiente `SONARR_URL`. Cambia da `192.168.0.2:8989` a `http://192.168.0.2:8989`

**Comment by JacopoBassan** [comment]
@MainKronos era quello, mia stupida svista, grazie!
