### ISSUE TITLE
[Enhancement] Ricerca per titoli alternativi di Sonarr

### ISSUE THREAD

**Issue by bonny1992** [MainKronos/Sonarr-AnimeDownloader#113]
### Settore
- Nucleo del programma

### È una richiesta relativa a un problema?
Se il programma non trova un particolare anime, è possibile invece trovarlo con un altro titolo, di solito Sonarr riporta il titolo in inglese, e su AnimeWorld è possibile sia in giapponese.

### Descrivi l'idea che hai in mente o che ti piacerebbe vedere realizzata.
Se la ricerca di un titolo fallisce, il programma prova a cercare anche i titoli alternativi (se ci sono).
Se è già ciò che faceva, chiedo scusa, monitorando i logs non penso di averlo notato però.

### Descrivi le alternative che hai considerato.
Cercarli a mano uno ad uno con l'aiuto dell'issue #111 

### Contenuto aggiuntivo
Nulla che mi venga in mente al momento.

**Comment by MainKronos** [comment]
Aggiunto nella versione dev grazie al contributo di @devaleriofrancesco [#135]
