### ISSUE TITLE
[BUG] Problema con episodi con numerazione non int (12.5)

### ISSUE THREAD

**Issue by bonny1992** [MainKronos/Sonarr-AnimeDownloader#118]
### Livello di Errore:
> _Selezionare solo un livello di errore_
- `🅴🆁🆁🅾🆁`

### Messaggio di Errore
```
🔎 Ricerca anime 'TONIKAWA: Over the Moon for You' stagione 1.
🔎 Ricerca episodio 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12.

─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ 
🅴🆁🆁🅾🆁: invalid literal for int() with base 10: '12.5'
Traceback (most recent call last):
  File "/script/job.py", line 44, in job
    episodi = fun.fixEps([x.getEpisodes() for x in results])
  File "/script/utility/functions.py", line 193, in fixEps
    up = int(eps[-1].number)
ValueError: invalid literal for int() with base 10: '12.5'
```

### Informazioni generali
> _Compilare i campi se correlato_
- **Nome Anime**: TONIKAWA: Over the Moon for You
- **Stagione**: 1
- **Episodio**: 12.5
- **Link di AnimeWorld**: 

### Descrizione [_Opzionale_]
Immagino che qualsiasi anime con episodi "intermedi" possa dare questo errore.

**Comment by MainKronos** [comment]
Il problema dovrebbe essere risolto nella versione dev. Devo ancora sistemare alcune cose prima di rilasciare la nuova versione.
Nel mentre puoi usare la versione dev, vedi [qui](https://github.com/MainKronos/Sonarr-AnimeDownloader/issues/115#issuecomment-1717142870)

**Comment by bonny1992** [comment]
Perfetto, provo subito.

**Comment by MainKronos** [comment]
Il problema è risolto nella versione Dev?

**Comment by bonny1992** [comment]
> Il problema è risolto nella versione Dev?

Si, il problema non si è ripresentato.
