### ISSUE TITLE
[BUG] Ridenominazione INTERA SERIE ANIME invece che l'episodio aggiunto!

### ISSUE THREAD

**Issue by zFerry98** [MainKronos/Sonarr-AnimeDownloader#12]
### Informazioni generali
* **Nome Anime**: RWBY
* **Stagione**: 08
* **Episodio**: 08
* **Link di AnimeWorld**: https://www.animeworld.tv/play/rwby-volume-08.GWabZ/tzicl8

**Livello di Errore:**
### Descrizione
_Ora gli episodi vengono spostati nella cartella giusta... ma la ridenominazione avviene per **l'intera serie!!**
Mi sono ritrovato tutte e 8 le stagioni di RWBY rinominate con "Sonarr" nel nome del gruppo! Invece che "Sonarr" solo per Ep 8 della 8va stagione. Per fortuna ho visto subito la cosa (1 giorno dopo) e ho fermato tutto... Minchia se impazzivo se mi trovavo nanatsu con 3 gruppi diversi come nome sostituito con Sonarr.
Bisogna far si che sonarr **NON RINOMINI L'INTERA SERIE** ma solo l'episodio che si sta aggiungendo.
Fortunatamente RWBY è fatto da soli due gruppi e quindi mi ci vuole poco a ripristinare (e anche sonarr ha un log con scritto che quel episodio è stato rinominato da A a B)...
Ti spiego dove sta il problema nel mio caso:
Io faccio i MUX delle serie passandole da una 720p Web/TV a una BD 1080p (dove possibile) ma soprattutto aggiungo tutti i possibili subs ita trovabili a quel MKV. Questo significa che per me il nome gruppo sarà:
"Nome Serie - s01e01 - Judas (la fonte video nuova) + Gruppo Fansub1 ITA + Gruppo Fansub2 ITA - Titolo Episodio, ecc. .mkv"
Mi serve sapere chi ho messo nel mux dal titolo oltre che dai titoli all'interno del MKV. Ora puoi immaginare che cosa succede se mi trovo nanatsu con 4 gruppi di nomi cancellati con Sonarr... Purtroppo Sonarr è stupido e NON MANTIENE il vecchio nome gruppo già presente nei file._

**Comment by MainKronos** [comment]
ok 😅, come soluzione provvisoria fai il downgrade alla versione precedente.
Io nel mentre sistemo il codice👍

**Comment by MainKronos** [comment]
Errore sistemato nella versione `1.3.0`

**Comment by zFerry98** [comment]
Risolto 👍👌
Ottimo anche per l'impostazione di non rinominare proprio i file 💪.
Ora come al solito vedo cosa combina in 2-3 settimane di test, Grazie del supporto.
