### ISSUE TITLE
[Enhancement] Pulsante "Ricerca Ora"

### ISSUE THREAD

**Issue by SavvyMeat** [MainKronos/Sonarr-AnimeDownloader#121]
### Settore
> _Seleziona l'ambito della tua richiesta._

- Interfaccia web
- Nucleo del programma

### È una richiesta relativa a un problema?
> _Descrivi in modo chiaro e conciso che tipo di problema si tratta. Es. Sono davvero frustrato quando [...]_

Alle volte capita che non venga scaricato un episodio per un qualsiasi problema, come può essere quello che il link inserito di animeworld non è più valido. Dopo avere sistemato il problema dovrei aspettare che il programma riprovi da solo a ricercare la serie problematica.

### Descrivi l'idea che hai in mente o che ti piacerebbe vedere realizzata.
> _Descrivi in modo chiaro e conciso che cosa vuoi che accada e come dovrebbe funzionare._

Avevo pensato ad un Flaoting Action Button nella pagina dei log per ripetere la ricerca. Per non stravolgere il core attuale, dato che al momento c'è un `if wait > 0: time.sleep(wait)`, la soluzione potrebbe essere semplicemente di farlo aspettare un minuto e controllare che non sia stata fatta una richiesta di ricerca.

### Descrivi le alternative che hai considerato.
> _Descrivi in modo chiaro e conciso quale idee, soluzioni o caratteristiche hai considerato._

Al momento ho uno script su home assistant che mi riavvia il container di animedownloader.

**Comment by TheDestr0yer** [comment]
Quoto anche io per questa features, al momento utilizzo uno script per riavviare il Container ma con una sezione per riavviare la ricerca direttamente dal log sarebbe ottima.

**Comment by MainKronos** [comment]
Aggiunto nella versione dev grazie al contributo di @devaleriofrancesco

**Comment by SavvyMeat** [comment]
Ho provato la funzionalità con l'immagine di dev. Mi sembra ottima, grazie.
