### ISSUE TITLE
[BUG] Dalla 2.0.0 non ha più funzionato

### ISSUE THREAD

**Issue by JacopoBassan** [MainKronos/Sonarr-AnimeDownloader#122]
### Livello di Errore:
Nessuno, stranamente?

### Messaggio di Errore
Non ne ho riscontrato nessuno nei log.

### Informazioni generali
In generale su varie serie che stavano funzionando con la versione precedente.

### Descrizione
A seguito dell'aggiornamento, dopo aver migrato anche le cartelle, si è correttamente preso la tabella e le altre impostazioni che avevo già impostato, ma non ha più scaricato nulla e non sta dando alcun tipo di errore.
Mi era capitato con la versione precedente di avere un link cambiato e relativo warning, di avere problemi con i permessi di scrittura e vedere l'errore, o di API di Sonarr, ora nulla di tutto ciò e non mi segnala alcun che. Sonarr nel mentre non è stato aggiornato ne modificato. Proverò probabilmente a tornare alla versione precedente giusto per capire se è un problema esterno.

**Comment by JacopoBassan** [comment]
Aggiungo un dubbio, è ancora compatibile con SonarrV3? Non sono sicuro di essere passato dalla [1.9.5] dove riportava
Aggiornamento APIv3 per la nuova versione di Sonarrv4

**Comment by MainKronos** [comment]
Si, la versione 2.0.0 supporta entrambe le versioni di Sonarr.
Mi alleghi il file dicker-compose che hai usato e il file di log?

**Comment by JacopoBassan** [comment]
Ho provato a ricambiare le cartelle e rilanciare il container sia con la 1.9.4 che con la 1.9.5 e ha istantaneamente riconosciuto gli ep mancanti e scaricati, rimetto la 2.0.0 e nulla.

Con DEBUG l'unica info che ho in più è che ha scartato 18 serie perché non presenti nella tabella di conversione, nulla di più di utile nei log ma se vuoi te lo passo comunque, questo avviene anche con la 1.9.X.

Sto usando docker da Synology DSM quindi non ho un docker-compose da allegarti ma non ho cambiato nulla più che le due cartelle tra i due container oltre alla versione, servisse posso mandarti le variabili d'ambiente che passo.

**Comment by JacopoBassan** [comment]
Ok ho appena notato una cosa, con la 1.9.X l'avviso di serie non presenti è più lunga e completa (tutte quelle che ho su sonarr, devo finire di sistemare e ordinarne alcune) mentre sulla 2.0.0 si ferma tutte le volte ad un titolo preciso, non so se può essere subentrato un bug sulla quantità di serie scartate o altro, non mi da altri log della serie di parsing di titoli ecc., ma credo non stia scaricando altri titoli perché non arriva a controllarli, allego un estratto di quello che vedo, se vuoi ti mando tutto.

1.9.X
[…altri titoli...]
❌ La 𝘴𝘦𝘳𝘪𝘦 'Magi: The Labyrinth of Magic' non esiste nella 𝗧𝗮𝗯𝗲𝗹𝗹𝗮 𝗗𝗶 𝗖𝗼𝗻𝘃𝗲𝗿𝘀𝗶𝗼𝗻𝗲.
❌ La 𝘴𝘦𝘳𝘪𝘦 'Is It Wrong to Try to Pick Up Girls in a Dungeon?' non esiste nella 𝗧𝗮𝗯𝗲𝗹𝗹𝗮 𝗗𝗶 𝗖𝗼𝗻𝘃𝗲𝗿𝘀𝗶𝗼𝗻𝗲.
[…altri titoli...]

2.0.0
[…altri titoli...]
❌ Serie 'Magi: The Labyrinth of Magic' scartata perchè non è presente nella TABELLA DI CONVERSIONE.
[FINE]

**Comment by MainKronos** [comment]
Per caso il numero di episodi che a sonarr risultano `missing`, compresi anime e non, superano i 1000?
Perchè avevo messo questo limite pensando di ottimizzare il numero di richieste, ma a quanto pare il limite è troppo basso 😅

**Comment by JacopoBassan** [comment]
Si confermo sono più di 1000, giusto per darti un'idea della situazione mentre sto ancora mettendo ordine:
`
Series
152
| Ended
121
| Continuing
31
| Monitored
152
| Unmonitored
0
| Episodes
6766
| Files
4738
`

Quindi `Missing 2028`

**Comment by bonny1992** [comment]
Anche io sono passato a riutilizzare la `1.9.5` per questo motivo.
Ho qualche episodio con la numerazione parziale (tipo `12.5`) che la versione non accettava ancora, ma li metto nella blacklist e via, fino alla soluzione.

**Comment by MainKronos** [comment]
Attualmente non posso rilasciare una nuova versione perché sto riscrivendo l'interfaccia in puro react, però ho aggiornato la versione dev con il fix di questo problema (e altri).
Se volete provarla:
```console
docker pull ghcr.io/mainkronos/anime_downloader:dev

docker-compose up
```

**Comment by Simoneu01** [comment]
Si con la versione dev è tornato a funzionare
