### ISSUE TITLE
[BUG] FileNotFoundError

### ISSUE THREAD

**Issue by Nikkano** [MainKronos/Sonarr-AnimeDownloader#127]
### Livello di Errore:
- **`Other`**

### Messaggio di Errore
> AnimeDownloader  | Traceback (most recent call last):
AnimeDownloader  |   File "/src/main.py", line 25, in <module>
AnimeDownloader  |     main()
AnimeDownloader  |   File "/src/main.py", line 7, in main
AnimeDownloader  |     core = Core()
AnimeDownloader  |   File "/src/components/backend/core/Core.py", line 49, in __init__
AnimeDownloader  |     self.tags = tags if tags else Tags(ctx.DATABASE_FOLDER.joinpath('tags.json'))
AnimeDownloader  |   File "/src/components/backend/database/Database.py", line 15, in __init__
AnimeDownloader  |     if not db.is_file(): raise FileNotFoundError()
AnimeDownloader  | FileNotFoundError

### Descrizione [_Opzionale_]
> Il container non riesce a partire, continua a restituirmi questo messaggio di errore all'inizio della partenza. Ho provato ad usare sia il compose che da cli specificati nella documentazione (cambiando i percorsi, la porta, e le info di Sonarr). Ho provato sia da Debian che da Windows.

**Comment by MainKronos** [comment]
Stranamente non viene creato in automatico il file [`tags.json`](https://github.com/MainKronos/Sonarr-AnimeDownloader/blob/main/src/database/tags.json). Prova a crearlo e metterlo nella cartella `/src/database/tags.json`

**Comment by Nikkano** [comment]
Ho provato a creare tags.json nella cartella ma e mi da un altro errore:
> AnimeDownloader  | Traceback (most recent call last):
AnimeDownloader  |   File "/src/main.py", line 25, in <module>
AnimeDownloader  |     main()
AnimeDownloader  |   File "/src/main.py", line 7, in main
AnimeDownloader  |     core = Core()
AnimeDownloader  |   File "/src/components/backend/core/Core.py", line 51, in __init__
AnimeDownloader  |     self.connections_db = connections_db if connections_db else ConnectionsDB(ctx.DATABASE_FOLDER.joinpath('connections.json'), ctx.SCRIPT_FOLDER)
AnimeDownloader  |   File "/src/components/backend/database/ConnectionsDB.py", line 17, in __init__
AnimeDownloader  |     super().__init__(db)
AnimeDownloader  |   File "/src/components/backend/database/Database.py", line 15, in __init__
AnimeDownloader  |     if not db.is_file(): raise FileNotFoundError()
AnimeDownloader  | FileNotFoundError

**Comment by berta24** [comment]
ma il docker ha permessi di lettura e scrittura in quella cartella?
Adesso non crea il file connections.json

**Comment by Nikkano** [comment]
Creando anche il file connections.json manualmente il container è partito senza problemi. Strano, perchè sembra che abbia i permessi di lettura e scrittura nella cartella
