### ISSUE TITLE
[BUG] Bug nei permessi, impossibile spostare l'anime

### ISSUE THREAD

**Issue by manuzzo24** [MainKronos/Sonarr-AnimeDownloader#130]
Ciao, 
fino a qualche mese fa usavo il downloader senza problemi sul mio Synology tramite Docker.
Tra aggiornamenti sia dell'OS che del container, ora mi ritrovo con questo errore, ogni qualvolta prova a scaricare un nuovo episodio.
Ho già verificato che PGID e PUID fossero corretti, che l'utente abbia i permessi su quelle relative cartelle, che siano le stesse cartelle di Sonarr, e di aver modificato i volumi utilizzando le 2 cartelle /src indicate nella guida
Ecco un estratto del log

2023/11/12 18:49:32	stdout	PermissionError: [Errno 13] Permission denied: '/anime/SPY x FAMILY/SPY x FAMILY - S2E2.mp4'
2023/11/12 18:49:32	stdout	    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
2023/11/12 18:49:32	stdout	  File "/usr/local/lib/python3.9/shutil.py", line 264, in copyfile
2023/11/12 18:49:32	stdout	    copyfile(src, dst, follow_symlinks=follow_symlinks)
2023/11/12 18:49:32	stdout	  File "/usr/local/lib/python3.9/shutil.py", line 435, in copy2
2023/11/12 18:49:32	stdout	    copy_function(src, real_dst)
2023/11/12 18:49:32	stdout	  File "/usr/local/lib/python3.9/shutil.py", line 826, in move
2023/11/12 18:49:32	stdout	    return shutil.move(src,dst)
2023/11/12 18:49:32	stdout	  File "/src/components/backend/core/Downloader.py", line 216, in __moveFile
2023/11/12 18:49:32	stdout	    if not self.__moveFile(file, destination):
2023/11/12 18:49:32	stdout	  File "/src/components/backend/core/Downloader.py", line 104, in download
2023/11/12 18:49:32	stdout	    self.downloader.download(serie)
2023/11/12 18:49:32	stdout	  File "/src/components/backend/core/Core.py", line 171, in job
2023/11/12 18:49:32	stdout	    self.job()
2023/11/12 18:49:32	stdout	  File "/src/components/backend/core/Core.py", line 140, in run
2023/11/12 18:49:32	stdout	Traceback (most recent call last):
2023/11/12 18:49:32	stdout	
2023/11/12 18:49:32	stdout	During handling of the above exception, another exception occurred:
2023/11/12 18:49:32	stdout	
2023/11/12 18:49:32	stdout	OSError: [Errno 18] Invalid cross-device link: '/downloads/SPY x FAMILY - S2E2.mp4' -> '/anime/SPY x FAMILY/SPY x FAMILY - S2E2.mp4'
2023/11/12 18:49:32	stdout	    os.rename(src, real_dst)
2023/11/12 18:49:32	stdout	  File "/usr/local/lib/python3.9/shutil.py", line 806, in move
2023/11/12 18:49:32	stdout	Traceback (most recent call last):
2023/11/12 18:49:32	stdout	ERROR    [Errno 13] Permission denied: '/anime/SPY x FAMILY/SPY x FAMILY - S2E2.mp4'
2023/11/12 18:49:32	stdout	CRITICAL ]─────────────────────────────────────────[CRITICAL]─────────────────────────────────────────[
2023/11/12 18:49:32	stdout	WARNING  ⏳ Spostamento episodio episodio S2E2 in /anime/SPY x FAMILY.
2023/11/12 18:49:32	stdout	INFO     ✔️ Dowload Completato.
2023/11/12 18:46:32	stdout	WARNING  ⏳ Download episodio S2E2.
2023/11/12 18:46:32	stdout	INFO     ✔️ L'episodio è disponibile.
2023/11/12 18:46:32	stdout	INFO     ⚙️ Verifica se l'episodio S2E2 è disponibile.
2023/11/12 18:46:32	stdout	INFO     
2023/11/12 18:46:31	stdout	INFO     🔎 Ricerca episodio 2, 3, 4, 5, 6.
2023/11/12 18:46:31	stdout	INFO     🔎 Ricerca serie 'SPY x FAMILY' stagione 2.

**Comment by MainKronos** [comment]
mi puoi allegare il docker-compose che hai usato e i permessi della cartella `/anime/SPY x FAMILY` (`$ ls -la`)?

**Comment by manuzzo24** [comment]
Grazie per il comando! Ho effettivamente visto tramite ssh che quella cartella (e Chainsaw Man) avevano i permessi scombussolati e mancavano quelli di scrittura!

Per i posteri: ho risolto con il comando chown -R nomeutente:users "SPY x FAMILY" e da File Station di Synology ho fatto tasto destro sulla cartella e dato i permessi di scrittura al gruppo utenti.

Si può chiudere! Grazie mille Lorenzo

![image](https://github.com/MainKronos/Sonarr-AnimeDownloader/assets/94800007/b07f7319-5aaa-417b-8ec1-bcdb4bccc401)
