### ISSUE TITLE
[BUG] Non salva le serie absolute nella tabella, rimangono vuote

### ISSUE THREAD

**Issue by Nikibasso94** [MainKronos/Sonarr-AnimeDownloader#133]
### Informazioni generali
 - **Nome Anime**: Naruto
 - **Stagione**: tutte
 - **Episodio**: tutti 
 - **Link di AnimeWorld**: https://www.animeworld.so/play/naruto.glnZ0/p5uzx

---

 - **Nome Anime**: Naruto Shippuden
 - **Stagione**: tutte
 - **Episodio**: tutti 
 - **Link di AnimeWorld**: https://www.animeworld.so/play/naruto-shippuden.v3U8a/ZXFbr

---

screen

![image](https://github.com/MainKronos/Sonarr-AnimeDownloader/assets/112549678/b7c75361-4be4-4545-957e-455078cb65c2)
![image](https://github.com/MainKronos/Sonarr-AnimeDownloader/assets/112549678/ded977dc-9776-445a-8d98-7b6c98bc8340)

### Descrizione
Ho provato a scaricare le serie di Naruto, ma non mi salva i link nella tabella di conversione
rimangono vuoti ho allegato gli screen

**Comment by bubez81** [comment]
si hai ragione non crea la stringa in modo corretto nel file table.json
io ho momentaneamente risolto modificando il file a mano e inserendo la stringa così:
[{"title": "Black Clover", "absolute": true, "seasons": {"absolute": ["https://www.animeworld.so/play/black-clover.MaMIb/fpBDR"]}}
esempio con anime Black Clover

**Comment by MainKronos** [comment]
Probabilmente è causato dal nuovo backend che ho riscritto per la versione 2.0.0

Come suggerito da @bubez81, come soluzione temporanea, è necessario modificare manualmente il file table.json per le serie ad ordinamento assoluto.

**Comment by MainKronos** [comment]
Risolto nella versione `dev`
