### ISSUE TITLE
[BUG] Serie Absolute non funzionanti

### ISSUE THREAD

**Issue by GreedTK** [MainKronos/Sonarr-AnimeDownloader#139]
### Livello di Errore:

- **`Other`**

### Messaggio di Errore

```
❌ Stagione absolute della serie 'One Piece' non è presente nella TABELLA DI CONVERSIONE.
```
### Informazioni generali

- **Nome Anime**: one piece
- **Stagione**:  absolute
- **Episodio**: 
- **Link di AnimeWorld**: https://www.animeworld.so/play/one-piece-ita.d5nahE

### Descrizione

Le serie che imposto come absolute vengono segnalate come non presenti nella tabella di conversione.
Analizzando il file table.json viene inserita così:
```json
{
        "absolute": true,
        "seasons": {},
        "title": "One Piece"
}
```
Sembra non salvare il link

**Comment by MainKronos** [comment]
Prova a rimuoverla e riaggiungerla dall'interfaccia

![Screenshot 2024-02-25 125425](https://github.com/MainKronos/Sonarr-AnimeDownloader/assets/21228689/f69669d6-0188-4856-8498-b5d02d2c8ece)

**Comment by GreedTK** [comment]
Ho provato ad aggiornare di nuovo il contenitore oggi ed ha funzionato.
Grazie mille @MainKronos!
