### ISSUE TITLE
[Error] int() with base 10: '5.5' _ Episodi ignorati

### ISSUE THREAD

**Issue by zFerry98** [MainKronos/Sonarr-AnimeDownloader#14]
### Informazioni generali
* **The Promised Neverland / One Piece**
* **2 / 21**
* **6 / 971+**
* **https://www.animeworld.tv/play/the-promised-neverland-2.HPGKr/Pt5U14**
* **https://www.animeworld.tv/play/one-piece-subita.j9hCX/HPKmX1**

### Livello di Errore:
- [ ] `🆆🅰🆁🅽🅸🅽🅶`
- [ ] `🅰🅻🅴🆁🆃`
- [x] `🅴🆁🆁🅾🆁`
- [ ] **`Other`**

### Messaggio di Errore
_invalid literal for int() with base 10: '5.5'_
_invalid literal for int() with base 10: '268-269'_

### Descrizione [_Opzionale_]
_
![image](https://user-images.githubusercontent.com/17975351/108632771-f164b400-7470-11eb-92de-3e63afed9638.png)
Posso capire l'episodio 5.5 che per Sonarr/Plex è un episodio della stagione 00 (specials) di TPN... One Piece invece non capisco perché. Andava e ora improvvisamente ha smesso dando quel errore.
Ho provato a cambiare il link mettendo anche la parte URL relativa a quel specifico episodio ma non è cambiato nulla. 
Ho anche cancellato dal json one piece e tpn e poi reinseriti e non è cambiato nulla.
_

**Comment by MainKronos** [comment]
Hahahahaah, sapevo che sarebbe successo prima o poi.... infatti ci stavo lavorando👍
Probabilmente il 23 rilascerò la correzione di questo bug
Mi spiace di non aver fatto in tempo😅

Come sempre grazie per la segnalazione👍

ah, se hai idee di miglioramenti o di aggiunta di nuove funzioni scrivi pure su [discussions](https://github.com/MainKronos/Sonarr-AnimeDownloader/discussions)

**Comment by MainKronos** [comment]
Ma sei sicuro che funziona correttamente il programma se scarichi One Piece (Tranne per l'ultimo errore)?
Perchè quella serie dava parecchi problemi visto che gli episodi sono tutti accorpati su AnimeWorld

**Comment by zFerry98** [comment]
> Ma sei sicuro che funziona correttamente il programma se scarichi One Piece (Tranne per l'ultimo errore)?
> Perchè quella serie dava parecchi problemi visto che gli episodi sono tutti accorpati su AnimeWorld

LoL, One Piece va... ma non con questo programma.
Siccome sonarr segnava verde One Piece pensavo fosse stato scaricato da questo programma.
Allora è solo TPN il problema.
Tutte le altre serie vanno senza problemi 👍

**Comment by MainKronos** [comment]
Prova la versione `1.3.2` dovrebbe risolvere il problema

**Comment by zFerry98** [comment]
LOL 🤣 ho visto ora che mi son scordato il titolo della issue hahahahaha.
Comunque... è un fix parziale (solo TPN) o comprendeva anche serie come One Piece?
Se fosse solo per serie come TPN, allora è tutto ok.

Log:
![image](https://user-images.githubusercontent.com/17975351/108997053-73d2bb00-769f-11eb-9e14-60e80234eef2.png)

One Piece - S21
Link: https://www.animeworld.tv/play/one-piece-subita.j9hCX

> ah, se hai idee di miglioramenti o di aggiunta di nuove funzioni scrivi pure su discussions

Magari appena trovo altro tempo ti aggiungo 2 - 3 cose 👍

**Comment by zFerry98** [comment]
Direi che il fix era solo per TPN, quindi chiudo ma ti consiglio di aprire una issue descrivendo il problema per le serie come One Piece. Idem se ci sono altri problemi noti NON ancora resi "pubblici" 👍💪👌
