### ISSUE TITLE
[QUESTION] Serie assolute (ma non assolute)

### ISSUE THREAD

**Issue by GreedTK** [MainKronos/Sonarr-AnimeDownloader#141]
### Descrizione
Su Animeworld, ad esempio, Fairy Tail, è diviso in 3 parti:
- La prima parte (https://www.animeworld.so/play/fairy-tail-ita.kdAKi/jn7Ofx) sono 175 episodi che compongono le prime 4 stagioni
- La seconda parte (https://www.animeworld.so/play/fairy-tail-2-ita.EMx8W/UyaxkN) sono 102 episodi che corrispondono alle stagioni 5-6-7
- La parte "finale" (https://www.animeworld.so/play/fairy-tail-final-series-ita.9oZOr/4nD0VM) che corrisponde alla stagione 8

Come posso inserire questa serie in Sonarr-AnimeDownloader?
Se metto il primo link come absolute, non posso aggiungere altri links.

### Conferma di presa visione
- [x] Confermo di aver controllato la sezione [FAQ](https://github.com/MainKronos/Sonarr-AnimeDownloader/blob/main/FAQ.md) e di non aver trovato nessuna soluzione al problema.
- [x] Confermo di aver controllato tra gli [Issue](https://github.com/MainKronos/Sonarr-AnimeDownloader/issues?q=is%3Aissue+label%3A%22help+wanted%22%2Cquestion%2Cdocumentation+-label%3A%22fixed+on+dev%22) e di non aver trovato nessuna soluzione al problema.

**Comment by MainKronos** [comment]
In che senso non puoi aggiungere altri links? Non ti funziona il pulsante `+` sotto al primo link della serie?
Se vuoi aggiungere più link relativi ad una singola stagione, devi prima aggiungere la serie con almeno un link, poi andare alla stagione appena aggiunta e sotto al primo link c'è un pulsante lungo con un `+` che serve per aggiungere altri link.

Credo che questo è il risultato che stai cercando di ottenere
![Screenshot 2024-05-01 193159](https://github.com/MainKronos/Sonarr-AnimeDownloader/assets/21228689/cfb8dedf-84c7-43af-88a1-c1cc83ed532d)

**Comment by GreedTK** [comment]
Grazie mille funziona, io le aggiungevo erroneamente come nuove season ma essendo absolute mi non funzionava.
Grazie
