### ISSUE TITLE
[QUESTION] Series Type

### ISSUE THREAD

**Issue by Taoshan98** [MainKronos/Sonarr-AnimeDownloader#142]
### Livello di Errore:
> _Selezionare solo un livello di errore_
- `🅴🆁🆁🅾🆁`

### Messaggio di Errore
- Serie 'Steins;Gate' scartata perchè non è di tipo anime.

### Informazioni generali
> _Compilare i campi se correlato_
- Nome Anime: Steins;Gate
- **Link di AnimeWorld**: https://www.animeworld.so/play/steins-gate-ita.8YRZD/JYlvF

### Descrizione [_Opzionale_]
> _Inserire qui una breve descrizione del problema._

In pratica stavo cercando di scaricare Steins;Gate da AnimeWorld, il problema è che non mi viene scaricata perchè, facendo un pò di debug, ho notato che la serie lato Sonarr viene salvata come 'standard' e di conseguenza il software la scarta.

Suggerirei che magari venga inserito un filtro più completo andando a scartare effettivamente se il nome della serie e coerente con quello di AnimeWorld, o magari farlo solo quando Sonarr risponde con 'Standard'.

**Comment by Taoshan98** [comment]
Aggiornamento:

Sono riuscito a modificare il tipo della serie tramite le api di Sonarr, ma ora il software mi fa un altro errore, ovvero: 
- Stagione 1 della serie 'Steins;Gate' non è presente nella TABELLA DI CONVERSIONE.
- Ricerca automatica url per la stagione 1 della serie 'Steins;Gate': nessun risultato trovato.

Forse questo dipende più da come ho configurato la serie, qualche suggerimento?

**Comment by MainKronos** [comment]
La serie deve essere necessariamente di tipo anime perchè altrimenti causerebbe dei problemi con gli algoritmi di indicizzazione che ci sono all'interno del programma.

La ricerca automatica è ancora abbastanza "sperimentale" e potrebbe non funzionare qualche volta.

Per collegare la serie di animeword con la stagione di sonarr basta utilizzare l'interfaccia web del programma, [qui](https://mainkronos.github.io/Sonarr-AnimeDownloader/usage/quickstart/#avvio) è descritto meglio

**Comment by Taoshan98** [comment]
> La serie deve essere necessariamente di tipo anime perchè altrimenti causerebbe dei problemi con gli algoritmi di indicizzazione che ci sono all'interno del programma.
> 
> La ricerca automatica è ancora abbastanza "sperimentale" e potrebbe non funzionare qualche volta.
> 
> Per collegare la serie di animeword con la stagione di sonarr basta utilizzare l'interfaccia web del programma, [qui](https://mainkronos.github.io/Sonarr-AnimeDownloader/usage/quickstart/#avvio) è descritto meglio

Capisco, alla fine l'unica soluzione al momento è stata modificare il tipo della serie tramite le API esposte da Sonarr.

**Comment by MainKronos** [comment]
Non è necessario usare le API. Basta premere `edit` e cambiare il tipo della serie
![Immagine 2024-07-10 203520](https://github.com/MainKronos/Sonarr-AnimeDownloader/assets/21228689/5c5fd01e-e68e-4be7-add8-c6f45044b2ac)
![Immagine 2024-07-10 203613](https://github.com/MainKronos/Sonarr-AnimeDownloader/assets/21228689/37e9bcd6-726c-4485-835f-a2689b019c35)
