### ISSUE TITLE
Container stopped randomly

### ISSUE THREAD

**Issue by xblood88** [MainKronos/Sonarr-AnimeDownloader#147]
Ciao ho installato il contenitore in una macchina unraid e funziona tutto bene solo che dopo un pò randomicamente trovo il contenitore in stop e lo devo riavviare a mano.

**Comment by MainKronos** [comment]
Puoi allegare il log di quando si ferma il container?

**Comment by berta24** [comment]
capitava anche a me, ho risolto mettendo come extra parametri `--restart unless-stopped`
![image](https://github.com/user-attachments/assets/579d4918-09d5-4eb5-b12c-d985b812c76a)

devi andare in modalità avanzata

**Comment by xblood88** [comment]
Grazie mille proverò.

Alberto Fontana

Il giorno 29 ott 2024, alle ore 19:42, berta24 ***@***.***> ha scritto:

﻿

capitava anche a me, ho risolto mettendo come extra parametri --restart unless-stopped
image.png (view on web)<https://github.com/user-attachments/assets/579d4918-09d5-4eb5-b12c-d985b812c76a>

devi andare in modalità avanzata

**Comment by berta24** [comment]
Ciao, hai provato alla fine? Funziona correttamente?

**Comment by xblood88** [comment]
Sì penso di sì ultimamente non ho messo niente in download ma non mi sembra di averlo visto stoppato. Grazie mille
