### ISSUE TITLE
One Piece errore episodi

### ISSUE THREAD

**Issue by MainKronos** [MainKronos/Sonarr-AnimeDownloader#16]
### Informazioni generali
* **Nome Anime**: One Piece
* **Stagione**: 1
* **Episodio**: 1
* **Link di AnimeWorld**:  https://www.animeworld.tv/play/one-piece-subita.j9hCX/HPKmX1

### Livello di Errore:
- [ ] `🆆🅰🆁🅽🅸🅽🅶`
- [ ] `🅰🅻🅴🆁🆃`
- [x] `🅴🆁🆁🅾🆁`
- [ ] **`Other`**

### Messaggio di Errore
errore map degli episodi

### Descrizione [_Opzionale_]
ordinamento episodi assoluti

**Comment by berta24** [comment]
Ciao, ma questo non è più stato risolto? ho provato recentemente ma mi da ancora errore con la stagione 20 e 21... Grazie mille in ogni caso, stai facendo un lavoro straordinario

**Comment by MainKronos** [comment]
in realtà ci stò ancora lavorando
il problema stà nella gestione di AnimeWorld per gli episodi che per quella serie usa il numero assoluto invece che un organizzazione per Stagione
Quindi il problema non accade solo per One Piece ma anche per gli anime organizzati nello stesso modo.

Avevo ideato di scrivere un'altra libreria che amplia già quella di [AnimeWorld-API](../tree/main/documentation/library) ma che usa anche molti altri siti in modo tale da tamponare il problema, cioè dove in un sito gli episodi sono gestiti male forse in un'altro saranno messi in ordine.
Il problema è che è abbastanza pesante renderla decente.... 😅

L'altra idea è gestire il caso in cui la serie sia organizzata con gli episodi assoluti. Qui il problema stà nel fatto che dovrei cambiare la struttura del file `table.json` e della pagina web (oltre ovviamente al codice) per aggiungere questa nuova impostazione per queste serie particolari. E questo sarebbe abbastanza scomodo per chi usa questo programma perchè dovrebbe riscrivere tutto il file `table.json` daccapo.

Quindi nel mentre stavo tentando con la prima idea...

**Comment by berta24** [comment]
Non so se può essere utile, ma nell'ultimo update di sonarr hanno aggiunto anche la numerazione assoluta degli episodi tenendo il mouse sopra il numero dell'episodio. Quindi teoricamente dovrebbe essere possibile adottare la numerazione assoluta.

**Comment by MainKronos** [comment]
Si, è possibile
Casomai faccio una versione sperimentale e vediamo un po' come viene

**Comment by MainKronos** [comment]
Credo di esser riuscito a risolvere il problema con la versione del docker Container `1.4.0-beta`.
Potrebbe essere instabile.... hahaha

Breve spiegazione delle novità:
- Per aggiungere un anime che segue la numerazione assoluta selezionare, nella pagina web, la checkbox absolute. Quindi il campo `Season` deve essere vuoto ![Immagine](https://user-images.githubusercontent.com/21228689/119054502-07c6d100-b9c8-11eb-8fc8-7184dc245b22.png)
- Se tutto è stato inserito correttamente apparirà un toast tipo questo: ![Immagine](https://user-images.githubusercontent.com/21228689/119054708-6be99500-b9c8-11eb-825a-4f0f539db0e9.png)
- E nell'elenco delle serie si potrà riconoscere facilmente gli anime impostati con un ordinamento assoluto grazie ad una targhettina come questa: ![Immagine](https://user-images.githubusercontent.com/21228689/119054929-bcf98900-b9c8-11eb-9da8-1cccf107d39e.png)
- Il file `table.json` è un po' cambiato, quindi va necessariamente aggiornato. Per facilitare la transazione dalla versione `1.3.x` alla `1.4.0` ho creato questo [script](../tree/beta/documentation/other/FixTable_1.3.x_to_1.4.x.py) python, basta avviarlo nella stessa cartella del file `table.json` e lo aggiorna alla nuova versione.

Il resto del funzionamento generale del programma è rimasto invariato. 👍
Se trovi bug o vuoi dei chiarimenti scrivi pure.
