### ISSUE TITLE
Installazione Raspberry Pi

### ISSUE THREAD

**Issue by EffeF** [MainKronos/Sonarr-AnimeDownloader#18]
Provando ad installarlo su Raspberry Pi, tramite Portainer, non funziona, e nei log ho il seguente messaggio di errore:
```logs
standard_init_linux.go:219: exec user process caused: exec format error
```
Immagino (forse?) che sia un problema di incompatibilità visto che la build della immagine è per amd64, su un sistema arm64.

Si può usare su Raspberry Pi?

**Comment by MainKronos** [comment]
mhh, non avevo pensato a questa eventualità 😅
Vedo se riesco a risolvere il problema 👍

**Comment by MainKronos** [comment]
Dovrei essere riuscito a creare un immagine multi-architettura👍
prova a scaricare l'ultima versione

**Comment by EffeF** [comment]
Installato, funziona tutto perfettamente adesso
