### ISSUE TITLE
Cartella download

### ISSUE THREAD

**Issue by berta24** [MainKronos/Sonarr-AnimeDownloader#2]
Aggiungendo un  nuovo anime, sonarr mi seleziona la cartella e la nomina con il nome dell'anime es. /tv/HunterXhunter, il problema è che la cartella non viene mai creata, e quando l'episodio viene scaricato, non viene mai spostato perché la cartella non esiste

**Comment by MainKronos** [comment]
puoi allegare i log?

**Comment by berta24** [comment]
Sono andato sui log per fare gli screen ma mi da un ulteriore problema ora, non mi cerca più gli anime,  nemmeno quelli che un tempo mi ha scaricato 
![errore](https://user-images.githubusercontent.com/25983005/103698308-766b3b00-4fa1-11eb-8bbb-e4724b5a85b0.png)

**Comment by MainKronos** [comment]
Probabilmente hanno aggiornato il sito AnimeWorld, spero di risolverlo in fretta

**Comment by MainKronos** [comment]
Dovrei aver risolto questo ultimo problema, mentre per quello iniziale non ho capito qual'è il problema....😅

**Comment by berta24** [comment]
Praticamente, i file vengono scaricati nella cartella config dell'container, successivamente vengono spostati nella cartella /tv/*nomeanime*. il problema è che la cartella in questione devo crearla io, altrimenti mi da Errno 2 No such file or directory
ES: ho messo in download l'episodio 1 di one piece, senza creare la cartella. 
![cartella2](https://user-images.githubusercontent.com/25983005/103777994-f04b0500-5031-11eb-9a10-c0a5b678fc8a.png)
![cartella](https://user-images.githubusercontent.com/25983005/103777853-c5f94780-5031-11eb-9f8c-86ac1577db44.png)

Mentre se io creo la cartella One piece 
![cartella3](https://user-images.githubusercontent.com/25983005/103778113-17093b80-5032-11eb-8ef0-119d8f8f2e61.png)
![cartella4](https://user-images.githubusercontent.com/25983005/103778662-dc53d300-5032-11eb-95a9-9c2ddece3385.png)

**Comment by MainKronos** [comment]
Tecnicamente la cartella dovrebbe crearla Sonarr, aggiungerò che se non trova la cartella la crea👍

**Comment by MainKronos** [comment]
Adesso se la cartella non esiste viene creata, spero di aver risolto il problema con la versione 0.3.2
