### ISSUE TITLE
🅰🅻🅴🆁🆃: Il sito è cambiato, di conseguenza la libreria è deprecata

### ISSUE THREAD

**Issue by zFerry98** [MainKronos/Sonarr-AnimeDownloader#21]
### Livello di Errore:
- [ ] `🆆🅰🆁🅽🅸🅽🅶`
- [x] `🅰🅻🅴🆁🆃`
- [ ] `🅴🆁🆁🅾🆁`
- [ ] **`Other`**

### Messaggio di Errore
![image](https://user-images.githubusercontent.com/17975351/116791927-d42a1280-aabd-11eb-9861-1d7ab6205ff2.png)

**Comment by MainKronos** [comment]
Mi puoi dire anche l'anime e la stagione che ha causato l'errore?

**Comment by MainKronos** [comment]
ok, quindi per un fix manuale scrivere questo comando nella console interna al docker: `pip install -U animeworld`
Altrimenti attendere la prossima immagine docker che dovrei rilasciare domani.

**Comment by zFerry98** [comment]
> Mi puoi dire anche l'anime e la stagione che ha causato l'errore?

🔎 Ricerca anime 'Edens Zero' per l'episodio S1E4.
🔎 Ricerca degli episodi per 'Edens Zero'.

Link: https://www.animeworld.tv/play/edens-zero.A3qCl/tba
Stagione: 01

**Comment by MainKronos** [comment]
Problema risolto con la versione `1.3.4`

**Comment by berta24** [comment]
![Immagine 2021-05-07 004441](https://user-images.githubusercontent.com/25983005/117374435-6d499680-aecd-11eb-9786-dbb725a91a4b.png)
https://www.animeworld.tv/play/arifureta-shokugyou-de-sekai-saikyou.tFVo1/QwCdA

**Comment by MainKronos** [comment]
Hanno ricambiato il sito.....
Devo trovare un modo per prevenire questo problema dei cookie...
Nel metre, per sistemare l'errore, scegliere uno delle seguenti soluzioni temporanee:
- Eseguire questo comando all'interno del Docker Container `pip install animeworld==1.3.2 --force-reinstall`
- Fare il downgrade del Docker Container alla versione `1.3.3`

Spero di risolvere il problema il prima possibile **e in modo permanente**😅

**Comment by MainKronos** [comment]
Problema _credo_ risolto nella versione [`1.3.5`](../releases/tag/1.3.5)
Speriamo che sia riuscito a prevedere i fututi mutamenti del sito....
Incrociamo le dita 😂

**Comment by berta24** [comment]
![Immagine 2021-05-13 223951](https://user-images.githubusercontent.com/25983005/118184917-3aa71d00-b43c-11eb-9ef0-804f438effb9.png)
**F** lo fa ancora

**Comment by MainKronos** [comment]
Hanno cambiato il nome del cookie che utilizzo per mantenere la sessione attiva 😭
30 minuti e sistemo

**Comment by MainKronos** [comment]
Adesso dovrebbe funzionare nuovamente con la versione [`1.3.6`](https://github.com/MainKronos/AnimeWorld-API/releases/tag/v1.3.6)

**Comment by zFerry98** [comment]
![image](https://user-images.githubusercontent.com/17975351/148747979-df325ea3-0915-403e-becc-5b3d1afea107.png)
 One Piece;
 con 1.5.2 (la versione pull di 10 ore fa).

**Comment by MainKronos** [comment]
Mi puoi scrivere anche il link di animeworld che usi per One Piece?

**Comment by zFerry98** [comment]
> Mi puoi scrivere anche il link di animeworld che usi per One Piece?

"https://www.animeworld.tv/play/rwby-volume-08.GWabZ/tzicl8"

**Comment by zFerry98** [comment]
> Mi puoi scrivere anche il link di animeworld che usi per One Piece?

"https://www.animeworld.tv/play/one-piece-subita.j9hCX/UTCQyC"

**Comment by MainKronos** [comment]
> > Mi puoi scrivere anche il link di animeworld che usi per One Piece?
> 
> "https://www.animeworld.tv/play/one-piece-subita.j9hCX/UTCQyC"

È un problema del link, probabilmente è stato cambiato da animeworld. Non so perchè facciano così.
In ogni caso per risolvere il problema basta che cambi il link con questo: `https://www.animeworld.tv/play/one-piece-subita.sORn4`.

Duplicate of #28

**Comment by zFerry98** [comment]
Lool!
OK, grazie.
È fattibile un errore di output specifico sul URL vecchio? (magari controllando tramite API quello nuovo)
Presumo di no, altrimenti non dovremmo noi immettere URL quando aggiungiamo la serie ma lo farebbe il programma in automatico.

**Comment by MainKronos** [comment]
### Informazioni generali
> _Compilare i campi_
* **Nome Anime**: L'attacco dei Giganti 4 Parte 2
* **Stagione**: 4
* **Episodio**: probabilmente tutti
* **Link di AnimeWorld**: https://www.animeworld.tv/play/lattacco-dei-giganti-4-parte-2.IsVqa/

### Livello di Errore:
- [ ] `🆆🅰🆁🅽🅸🅽🅶`
- [ ] `🅰🅻🅴🆁🆃`
- [ ] `🅴🆁🆁🅾🆁`
- [x] **`Other`**

### Descrizione
La libreria non costruisce bene il link dell'episodio che si trova su Streamtape, quindi scarica un video di 20 secondi di errore (un tizio che parla in inglese che mi sbeffeggia perchè non sono riuscito a scaricare il video che volevo).
Probabilmente hanno nuovamente cambiato il sito.... 😢

**Comment by MainKronos** [comment]
Risolto con la versione [`1.5.4`](https://github.com/MainKronos/Sonarr-AnimeDownloader/releases/tag/1.5.4)

**Comment by grievertime** [comment]
Ciao, mi dispiace riaprire, con la 1.7.3
⚠️ Ricerca automatica link di AnimeWorld per la 𝘴𝘵𝘢𝘨𝘪𝘰𝘯𝘦 5 della 𝘴𝘦𝘳𝘪𝘦 'Monogatari'.
🅴🆁🆁🅾🆁: Il sito è cambiato, di conseguenza la libreria è DEPRECATA. -> [find - 77]
`Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/animeworld/utility.py", line 23, in wrapper
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/animeworld/utility.py", line 77, in find
    myHDR = {"csrf-token": soupeddata.find('meta', {'id': 'csrf-token'}).get('content')}
AttributeError: 'NoneType' object has no attribute 'get'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/script/anime_downloader/__init__.py", line 23, in job
    series = converting(raw_series)
  File "/script/anime_downloader/functions.py", line 135, in converting
    link = linkSearch(anime["title"], season["num"], anime["tvdbID"])
  File "/script/anime_downloader/functions.py", line 59, in linkSearch
    result = bindAnime(title, int(season), tvdbID)
  File "/script/anime_downloader/functions.py", line 212, in bindAnime
    results = aw.find(anime_name)
  File "/usr/local/lib/python3.9/site-packages/animeworld/utility.py", line 28, in wrapper
    raise DeprecatedLibrary(funName, errLine)
animeworld.exceptions.DeprecatedLibrary: Il sito è cambiato, di conseguenza la libreria è DEPRECATA. -> [find - 77]`

**Comment by MainKronos** [comment]
Probabilmente quelli di animeworld hanno modificato un po' il loro codice
Comunque ho rilasciato la nuova versione della libreria ([v1.4.15](https://github.com/MainKronos/AnimeWorld-API/releases/tag/v1.4.15)) prova ad aggiornarla `pip install -U animeworld`

**Comment by berta24** [comment]
![image](https://user-images.githubusercontent.com/25983005/163401884-d40e64af-a89d-44ac-8f18-302bf48d9d82.png)

Ho aggiornato la libreria, tutto bene, ho riavviato e non parte più del tutto

**Comment by MainKronos** [comment]
Scusatemi per il disagio, mi sono dimenticato di aggiornare una costante...
Eseguite questi comandi e dovrebbe risolversi tutto:
```bash
pip uninstall animeworld
pip install -U animeworld
```

**Comment by Simoneu01** [comment]
> Scusatemi per il disagio, mi sono dimenticato di aggiornare una costante... Eseguite questi comandi e dovrebbe risolversi tutto:
> 
> ```shell
> pip uninstall animeworld
> pip install -U animeworld
> ```

É possibile taggare una release? Non riesco ad aggiornare la libreria tramite pip.

**Comment by MainKronos** [comment]
Ancora non è stata rilasciata una release, verrà distribuita in questi giorni. Prima di rilasciarla volevo anche sistemare l'errore #50 .

Per aggiornare la libreria (per ora) è necessario essere root 😅, quindi devi accedere dentro al container come root.

**Comment by MainKronos** [comment]
Risolto con la versione [1.7.4](https://github.com/MainKronos/Sonarr-AnimeDownloader/releases/tag/1.7.4)

**Comment by MainKronos** [comment]
Dopo un po' di tempo quelli di animeworld sono riusciti a fregarmi di nuovo.
```
🅰🅻🅴🆁🆃: Il sito è cambiato, di conseguenza la libreria è DEPRECATA. -> [File /usr/local/lib/python3.9/site-packages/animeworld/utility.py in fixCookie - 42]
```

Hanno modificato il nome del cookie necessario al caricamento della pagina, da `AWCookieVerify` a `SecurityAW`, e furbamente offuscato il codice in javascript per la sua generazione.

Il problema è nella funzione [`fixCookie`](https://github.com/MainKronos/AnimeWorld-API/blob/v1.4.19/animeworld/utility.py#L25-L43). Questa volta ci vorrà un po' per sistemarlo.

**Comment by ManuJapan89** [comment]
@MainKronos piu o meno riesci a quantificare quanto? :D io posso solo incentivare economicamente LOL non ne capisco molto :) ma sto sistema è vitale per la mia sanità mentale XD

**Comment by Simoneu01** [comment]
@MainKronos ho trovato un modo per risolvere solo che bisogna integrare un pacchetto extra, a breve apro un PR poi valuti te

**Comment by Simoneu01** [comment]
@MainKronos PR aperta

**Comment by ManuJapan89** [comment]
domanda, ma dite che l'han fatto apposta per il vostro software? mi sembra allucinante se fosse cosi....

**Comment by MainKronos** [comment]
> domanda, ma dite che l'han fatto apposta per il vostro software? mi sembra allucinante se fosse cosi....

non solo per il mia ma per tutti i programmi che si appoggiano al loro sito, io ed il team di animeworld siamo in pessimi rapporti.

Ti invito a leggere questo issue per farti un idea: #6

**Comment by ManuJapan89** [comment]
A me ha ripreso a scaricare da solo quindi si :)
