### ISSUE TITLE
Errore 404 per il download del convertitore di tabelle 1.3.x a 1.4.x.py

### ISSUE THREAD

**Issue by zFerry98** [MainKronos/Sonarr-AnimeDownloader#24]
### Livello di Errore:
- [ ] `🆆🅰🆁🅽🅸🅽🅶`
- [ ] `🅰🅻🅴🆁🆃`
- [ ] `🅴🆁🆁🅾🆁`
- [x] **`Other`**

_Il .py per convertire le tabelle .json 1.3.x a 1.4.x da errore 404 quando provi ad aprire il link_

![Immagine](https://user-images.githubusercontent.com/17975351/119257021-b84cf480-bbc3-11eb-9d42-aedd966c6582.png)

----------------------------------------------------------------------------------------------------------------------------------------------
_Inoltre non auto-crea una nuova tabella "pulita" se svuoti la cartella DATA dalla precedente tabella:_
![image](https://user-images.githubusercontent.com/17975351/119257285-db2bd880-bbc4-11eb-9614-7f32b7b535ea.png)
 
Errore simile se si crea un file vuoto che si chiama "table.json":
![image](https://user-images.githubusercontent.com/17975351/119257339-1c23ed00-bbc5-11eb-9a0f-65e1d8232b3b.png)

**Comment by MainKronos** [comment]
Hai ragione, dovrei aggiungere questa cosa....
Quindi se non c'è il file `table.json`, per ora, và aggiunto a mano. Puoi usare questo [`table.json`](..//blob/main/config/json/table.json)

Per il file `FixTable_1.3.x_to_1.4.x` lo puoi trovare [qui](../blob/main/documentation/other/FixTable_1.3.x_to_1.4.x.py)
Probabilmente avevo scritto male l'url nella documentazione, ora lo correggo subito
