### ISSUE TITLE
Errore all'avvio del container

### ISSUE THREAD

**Issue by grievertime** [MainKronos/Sonarr-AnimeDownloader#25]
Ciao!
avviando il container, con o senza serie configurate per il download, ho questo errore:

### Informazioni generali
Errore all'avvio del container

### Livello di Errore:
- [ ] `🆆🅰🆁🅽🅸🅽🅶`

### Messaggio di Errore
```
Traceback (most recent call last):
  File "/script/main.py", line 359, in <module>
    main()
  File "/script/main.py", line 77, in main
    job() # Fa una prima esecuzione e poi lo imposta per la ripetizione periodica
  File "/script/main.py", line 93, in job
    raw_series = get_missing_episodes()
  File "/script/main.py", line 286, in get_missing_episodes
    info["rawEpisode"] = int(serie["absoluteEpisodeNumber"])
KeyError: 'absoluteEpisodeNumber'

```

**Comment by MainKronos** [comment]
Che strano...
Che versione usi di Sonarr?
E usi l'ultima versione ([`1.4.1`](../releases/tag/1.4.1)) di questo Docker Container (*Sonarr-AnimeDownloader*)?

Comunque entro oggi provo a sistemare questo errore 👍

**Comment by grievertime** [comment]
Uso la versione di Sonarr: 3.0.6.1265 ( container ghcr.io/linuxserver/sonarr:latest)
Uso il container mainkronos/anime_downloader:1.4.1 (usavo il mainkronos/anime_downloader:latest che è lo stesso immagino )

Posso darti qualche altro dato utile al debugging?

**Comment by grievertime** [comment]
Tutto funzionante, grazie mille!
