### ISSUE TITLE
Bug spostamento file

### ISSUE THREAD

**Issue by berta24** [MainKronos/Sonarr-AnimeDownloader#26]
![bug](https://user-images.githubusercontent.com/25983005/124451315-8d8aba00-dd85-11eb-9f30-943659a1cee7.png)
Con episodi random da questo errore, non li sposta nella cartella giusta,

**Comment by MainKronos** [comment]
L'errore avviene solo quando deve creare la cartella? O completamente a caso?
Quindi il file alla fine non si trova nella cartella? Rimane all'interno del Docker Container nella cartella `/script` ?

**Comment by berta24** [comment]
![Immagine 2021-07-05 124820](https://user-images.githubusercontent.com/25983005/124460156-4acddf80-dd8f-11eb-855b-917155bca2f3.png)
li sposta nella cartella dell'anime ma non li mette nelle cartelle delle stagioni dandomi quell'errore
![Immagine 2021-07-05 124951](https://user-images.githubusercontent.com/25983005/124460325-85d01300-dd8f-11eb-8b75-d2b5c38c5b48.png)
i numeri degli episodi variano sempre

**Comment by MainKronos** [comment]
Credo di aver capito il problema.
Quando scarica il primo episodio la cartella della stagione ancora non esiste e il tempo per crearla e per spostare il file è più lungo del tempo di attesa che ho scritto nel codice ([qui](../blob/1.4.3/config/main.py#L135)). Quindi quel file ancora non è presente quando parte la scansione per rinominare l'episodio e metterlo nella giusta cartella .

Lo sistemerò il prima possibile 👍

**Comment by MainKronos** [comment]
Prova con la nuova versione '1.4.4' e poi dimmi se l'errore è stato risolto 👍

**Comment by Simoneu01** [comment]
Stesso problema anche io, la cartella però si chiama "stagione" invece che "season" non so se può servire. @MainKronos
