### ISSUE TITLE
Crash anomalo

### ISSUE THREAD

**Issue by berta24** [MainKronos/Sonarr-AnimeDownloader#27]
Ciao, dopo tot giorni che il docker è in funzione mi crasha dandomi questi errori, dopo il riavvio torna tutto normale, non è un enorme fastidio perché si risolve facilmente, ma volevo informarti 

![C2FBACD1-69C6-4F0D-A95F-20EC375F4251](https://user-images.githubusercontent.com/25983005/128270829-e60cc273-3940-49ea-bc91-5d5cd6136f21.png)
![DAC60662-0F87-4604-9505-F4406E7991E3](https://user-images.githubusercontent.com/25983005/128270834-143fed78-a8cb-422d-b446-ec0178538fe1.png)
![EB51FD1C-754C-48EB-8797-3CB627AA8FCC](https://user-images.githubusercontent.com/25983005/128270837-3078def0-41db-4f31-bd17-dc79aecd3aeb.png)

**Comment by MainKronos** [comment]
ok, grazie per la segnalazione
provvederò quanto prima a risolvere
