### ISSUE TITLE
feature request: cartella download

### ISSUE THREAD

**Issue by Simoneu01** [MainKronos/Sonarr-AnimeDownloader#29]
### Livello di Errore:
- **`Other`**

### Descrizione [_Opzionale_]
vorrei avere la possibilità di impostare la cartella download.

Se cortesemente indichi nella documentazione la cartella utilizzata la sovrascrivo con il volume di docker.

**Comment by Simoneu01** [comment]
ok ho visto che li scarica nella cartella /scripts

è possibile richiedere in una futura versione la possibilità di metterli in una cartella specifica?

**Comment by MainKronos** [comment]
Hai ragione, non ci avevo pensato. Effettivamente sarebbe più comodo se i download li facesse in una cartella dedicata.
Nella prossima release lo implementerò. (probabilmente uscirà il 02/01/2022)

**Comment by MainKronos** [comment]
Risolto con la versione `1.5.0`.
