### ISSUE TITLE
'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by MainKronos** [MainKronos/Sonarr-AnimeDownloader#3]
Sono andato sui log per fare gli screen ma mi da un ulteriore problema ora, non mi cerca più gli anime,  nemmeno quelli che un tempo mi ha scaricato 
![errore](https://user-images.githubusercontent.com/25983005/103698308-766b3b00-4fa1-11eb-8bbb-e4724b5a85b0.png)

_Originally posted by @berta24 in https://github.com/MainKronos/Sonarr-AnimeDownloader/issues/2#issuecomment-754896407_

**Comment by MainKronos** [comment]
Questo è risolto, avevano cambiato il nome ad un link.
Ho rilasciato la nuova versione 0.3.1

**Comment by berta24** [comment]
Questo è il mio table.json
anzi il tuo perché è ancora originale, non l'ho modificato. Non sono presenti altre dichiarazioni su attack on titan.
![attack on](https://user-images.githubusercontent.com/25983005/103776974-83833b00-5030-11eb-8a84-2db211889482.png)

Ma nei log del programma mi da ancora lo stesso errore, e mi prende un Server diverso da quello specificato 
![attack 2](https://user-images.githubusercontent.com/25983005/103777135-b9282400-5030-11eb-90b2-bba45c137e86.png)

**Comment by MainKronos** [comment]
vuol dire che hanno modificato anche la sezione di VVVVID, dovrò modificare anche quella😓
Grazie per la segnalazione....

**Comment by berta24** [comment]
Ma nella table è specificato che il file lo deve prendere da animeWorld, e infatti il primo risultato viene proprio da AnimeWorld Server

**Comment by MainKronos** [comment]
Nella table non è indicato il server da dove andare a prendere l'episodio:
![Immagine](https://user-images.githubusercontent.com/21228689/103778896-394f8900-5033-11eb-8c2f-25f4f0d314e8.png)

ma è indicato solo il nome dell'anime di riferimento su animeWorld, cioè questo:
![Immagine](https://user-images.githubusercontent.com/21228689/103779053-7b78ca80-5033-11eb-8c88-c0bdc9afcbeb.png)

**Comment by berta24** [comment]
> vuol dire che hanno modificato anche la sezione di VVVVID, dovrò modificare anche quella😓
> Grazie per la segnalazione....

mentre tutti quelli su youtube mi danno:
Il file si trova su 𝐘𝐨𝐮𝐓𝐮𝐛𝐞
🅴🆁🆁🅾🆁🅴: list index out of range

**Comment by MainKronos** [comment]
quale anime ti da quell'errore?

**Comment by MainKronos** [comment]
Con la versione 0.3.2 dovrebbe funzionare tutto come prima🤞

**Comment by MainKronos** [comment]
Hanno nuovamente cambiato il nome ai link, è in corso il nuovo aggiornamento👍

**Comment by MainKronos** [comment]
Nuova versione!! `0.3.3`
