### ISSUE TITLE
feature request: Rimuovere dalla gestione le serie tv

### ISSUE THREAD

**Issue by Simoneu01** [MainKronos/Sonarr-AnimeDownloader#32]
Attualmente nel log mi sembra che il software faccia richieste API per ogni tipo serie senza fare distinzione tra Anime / serie TV.

Consiglierei di lasciare nel logging e nel processing solo le serie di tipo "Anime"

La chiave da usare ne json è: `seriesType`

` seriesType: 'standard' | 'daily' | 'anime'`

Docs: https://github.com/Sonarr/Sonarr/wiki/Series

Aggiungendo quindi un ulteriore check in questo punto:
https://github.com/MainKronos/Sonarr-AnimeDownloader/blob/main/config/main.py#L291

**Comment by MainKronos** [comment]
Risolto con la versione `1.5.0`.

**Comment by berta24** [comment]
il problema è che sonar aggiunge di default tutte le serie come standard, e quindi adesso c'è da modificare il campo ogni volta che si fa un inserimento nuovo, e anche tutte le serie in corso vanno cambiate...

**Comment by Simoneu01** [comment]
Puoi modificare il blocco tutto, io personalmente utilizzo Overseer per gestire le richieste e automaticamente mette anime

**Comment by berta24** [comment]
ok molto carino Overseerr, l'ho configurato e funziona bene
