### ISSUE TITLE
Request -- Piccola modifica QoL log

### ISSUE THREAD

**Issue by berta24** [MainKronos/Sonarr-AnimeDownloader#38]
Se fosse possibile aggiungere ai log di download la dimensione dell'episodio in download, la percentuale completata e la velocità di download magari un update ogni 5 secondi, almeno per avere una sorta di storico di quanto ci potrebbe mettere...
è puramente una modifica QoL

**Comment by berta24** [comment]
Ciao, dato che questo issue è ancora aperto chiedo se sia possibile aggiungere anche un messaggio su telegram, dove in caso la ricerca automatica fallisca (o in generale se l'anime non è presente nella tabella di conversione) l'utente venga segnalato subito in modo che possa correggere l'eventuale problematica del link

**Comment by MainKronos** [comment]
Aggiunta la barra di progresso con le relative informazioni con la versione `1.7.2`. Non è stato possibile inserirlo in forma testuale nel log perchè rompeva completamente tutta la formattazione.
Credo che questa barra di progresso sia stata una delle cose più complicate e apparentemente banali che abbia mai fatto 😂

Per quanto riguarda la notifica telegram, ho ritenuto migliore notificare l'utente quando viene trovato un risultato che quando non accade, perchè quando trova qualcosa viene modificata la tabella e questa operazione potrebbe fare danni, e quindi l'utente dovrebbe esser notificato; Se invece ci fosse una notifica per ogni volta che fallisce questo processo, l'utente si ritroverebbe bombardato di messaggi ogni 30 minuti😅
