### ISSUE TITLE
Ottimizzazione Prestazioni

### ISSUE THREAD

**Issue by berta24** [MainKronos/Sonarr-AnimeDownloader#40]
Ci mette molto di più a iniziare a scaricare un episodio (10min solo per iniziare) perché si inchioda qui:

![image](https://user-images.githubusercontent.com/25983005/151399786-91c9aa67-311c-43ac-8b4c-b910f365af04.png)

Sia con la funzionalità attiva che spenta

**Comment by MainKronos** [comment]
hahaahah, credo che sia un problema di ottimizzazione
Probabilmente è perchè ci sono molti episodi, per ogni episodio fà una richiesta POST per ottenere le informazioni 😂.
Se solo avessi accesso alle API interne non sarei costretto a bombardargli il sito per il web Scraping 😢... 
ci dovrei rimettere mano....

**Comment by Simoneu01** [comment]
una cosa che si potrebbe fare per ottimizzare è che quando controlla un anime se un episodio manca salta direttamente tutto l'anime invece che cercare tutti gli episodi successivi

**Comment by berta24** [comment]
> una cosa che si potrebbe fare per ottimizzare è che quando controlla un anime se un episodio manca salta direttamente tutto l'anime invece che cercare tutti gli episodi successivi

eh ma il problema è che questo anime esiste nella tabella di conversione, ma lo cerca lo stesso anche se esiste

**Comment by Simoneu01** [comment]
> ok, prova ad aggiornare la libreria alla versione `1.4.7`
> 
> ```
> pip install animeworld -U
> ```
> 
> Dovrebbe essere molto meglio

Non so se era riferito al mio commento, nel caso ho provato comunque e non sembra essere cambiato:
![image](https://user-images.githubusercontent.com/43807696/151434218-0b217da3-3058-4b98-8a7f-09aaaee7c722.png)

**Comment by MainKronos** [comment]
Era riferito al commento iniziale di questo Issue 😅
Comunque posso vedere che comunque non ci mette più 10 minuti.

Sarebbe possibile ottimizzare ancora di più unificando la ricerca ti tutti gli episodi appartenenti ad una stessa stagione, ma è parecchio rognoso... è da un anno che lo voglio fare😂
Prima o poi lo farò

**Comment by MainKronos** [comment]
Con la stagione `1.7.1` sono riuscito ad accorpare insieme tutti gli episodi appartenenti ad una stagione durante la ricerca; in questo modo dovrei aver notevolmente ridotto i tempi, soprattutto per gli anime che seguono una numerazione assoluta come One-Piece.
