### ISSUE TITLE
Modifica campo link direttamente da Tabella di conversione

### ISSUE THREAD

**Issue by berta24** [MainKronos/Sonarr-AnimeDownloader#42]
-Request: Possibilità di modificare il campo link direttamente dalla tabella di conversione come con il nome dell'anime, in questo modo quando in automatico aggiunge un link, se c'è da fare una modifica si può fare al volo senza agire sui file direttamente

**Comment by MainKronos** [comment]
Aggiunto con la versione [`1.7.0`](https://github.com/MainKronos/Sonarr-AnimeDownloader/releases/tag/1.7.0)

Per maggiori informazioni guardare anche [qui](https://github.com/MainKronos/Sonarr-AnimeDownloader/blob/1.7.0/FAQ.md#devo-cancellaremodificare-un-linkstagioneanime)
