### ISSUE TITLE
Bug: download completato ma fallisce la rinomina e lo spostamento del file

### ISSUE THREAD

**Issue by Simoneu01** [MainKronos/Sonarr-AnimeDownloader#43]
### Informazioni generali
* **Nome Anime**:  CUE!
* **Stagione**:  1
* **Episodio**:  6
* **Link di AnimeWorld**: 

### Livello di Errore:
- `🅴🆁🆁🅾🆁`

### Messaggio di Errore
![image](https://user-images.githubusercontent.com/43807696/153725801-be99e6ac-f461-41bf-91a4-f26b63ad6012.png)
![image](https://user-images.githubusercontent.com/43807696/153725873-3baa2de1-1eaa-419c-a7c5-daa47071b3aa.png)

**Comment by berta24** [comment]
![image](https://user-images.githubusercontent.com/25983005/153725920-446b9efe-f0d9-4e97-9b8d-5a2720e55dfd.png)
ho avuto lo stesso problema ieri sera...

**Comment by MainKronos** [comment]
Ho avuto anche io gli stessi errori, e la cosa strana che accade sempre con gli stessi anime
Stavo indagando da un paio di giorni

Mi potete scrivere sotto questo messaggio tutti gli anime che vi danno questo problema?

**Comment by Simoneu01** [comment]
Anime:
Yashahime: Princess Half-Demon
CUE!

**Comment by berta24** [comment]
anime per ora:
Arifureta: From Commonplace to World's Strongest
World's End Harem

il problema più che la notifica è il fatto che non li rinomina e non lo sposta nella cartella completati...

**Comment by MainKronos** [comment]
Fix con la versione [`1.6.2-alpha`](https://github.com/MainKronos/Sonarr-AnimeDownloader/releases/tag/1.6.2-alpha)
