### ISSUE TITLE
[Feature Request] Funzione "Bind" automatico solo per le serie già nella tabella.

### ISSUE THREAD

**Issue by VegethB** [MainKronos/Sonarr-AnimeDownloader#45]
**Mi è venuto un infarto quando più di 25 serie sono state aggiunte in automatico!**
Sonarr si gestisce già tutte le serie che vengono rilasciate per torrents, solo che (_con l'ultima di one piece che è cambiato il link a caso_) era comodo avere un autolink search per SOLO le serie nella tabella.

Basterebbe che sfrutti i tags (del tipo: se quel tags è presente nella serie, allora scaricala / aggiungila alla tabella; oppure, se non c'è quel tags ecc.).
Per esempio:
One Piece su Sonarr con tag "Sonarr-AnimeDownloader" = aggiungilo alla tabella perché hai trovato il "tag key" e fai la scansione + download di episodi.

È una ipotesi / feature request.
Per il resto non ho avuto più problemi da un po.

**Comment by MainKronos** [comment]
Con la versione `1.7.1` ho reso non disponibile la funzione di ricerca automatica link di AnimeWorld per le serie che seguono un ordinamento assoluto.
In questo modo sicuramente si evita problemi come quello che ti è successo, visto che le serie con ordinamento assoluto sono un po' particolari e che qualunque risultato riuscirebbe a trovare sarebbe sicuramente sbagliato.

Per ora dovrebbe essere abbastanza stabile, rimarrà così finche non mi viene in mente un idea più elegante

**Comment by MainKronos** [comment]
Con la nuova versione [`1.9.0`](https://github.com/MainKronos/Sonarr-AnimeDownloader/releases/tag/1.9.0) è possibile utilizzare i Tag per filtrare gli anime da scaricare, se un anime viene escluso non avviene nemmeno la ricerca automatica dei link di Animeworld.

Per maggiori informazioni sui tag leggere le [FAQ](https://github.com/MainKronos/Sonarr-AnimeDownloader/blob/main/FAQ.md#come-si-usano-i-tag) e per le modalità andare sul README alla sezione [Settings](https://github.com/MainKronos/Sonarr-AnimeDownloader/blob/main/README.md#settings).
