### ISSUE TITLE
ERROR - Auto ricerca link con stagione 0

### ISSUE THREAD

**Issue by grievertime** [MainKronos/Sonarr-AnimeDownloader#48]
### Informazioni generali
* **Nome Anime**:  Last Exile
* **Stagione**:  0

### Livello di Errore:
- `🅴🆁🆁🅾🆁`

### Messaggio di Errore
La 𝘴𝘦𝘳𝘪𝘦 'Last Exile' non esiste nella 𝗧𝗮𝗯𝗲𝗹𝗹𝗮 𝗗𝗶 𝗖𝗼𝗻𝘃𝗲𝗿𝘀𝗶𝗼𝗻𝗲.
⚠️ Ricerca automatica link di AnimeWorld per la 𝘴𝘵𝘢𝘨𝘪𝘰𝘯𝘦 0 della 𝘴𝘦𝘳𝘪𝘦 'Last Exile'.
🅴🆁🆁🅾🆁: list index out of range
```
Traceback (most recent call last):
  File "/script/anime_downloader/__init__.py", line 23, in job
    series = converting(raw_series)
  File "/script/anime_downloader/functions.py", line 132, in converting
    link = linkSearch(anime["title"], season["num"], anime["tvdbID"])
  File "/script/anime_downloader/functions.py", line 59, in linkSearch
    result = bindAnime(title, int(season), tvdbID)
  File "/script/anime_downloader/functions.py", line 231, in bindAnime
    "name": ret[season-1]["name"],
IndexError: list index out of range
```

### Descrizione [_Opzionale_]
Il problema nasce quando su sonarr si seleziona la stagione "Specials" (gestita come stagione 0 da sonarr) e si ha l'auto ricerca link attiva.

**Comment by berta24** [comment]
Credo che questo problema sia legato a quello sopra descritto 

![image](https://user-images.githubusercontent.com/25983005/162899195-07cfec87-402b-4e3e-b94c-e96b68a6e394.png)
---------------
il link è https://www.animeworld.tv/play/ascendance-of-a-bookworm-3.l5fru

![image](https://user-images.githubusercontent.com/25983005/162899273-e572e46e-26e7-46c4-8859-dab11a7ec24d.png)

**Comment by MainKronos** [comment]
> ### Informazioni generali
> * **Nome Anime**:  Last Exile
> * **Stagione**:  0
> 
> ### Livello di Errore:
> * `🅴🆁🆁🅾🆁`
> 
> ### Messaggio di Errore
> La 𝘴𝘦𝘳𝘪𝘦 'Last Exile' non esiste nella 𝗧𝗮𝗯𝗲𝗹𝗹𝗮 𝗗𝗶 𝗖𝗼𝗻𝘃𝗲𝗿𝘀𝗶𝗼𝗻𝗲. ⚠️ Ricerca automatica link di AnimeWorld per la 𝘴𝘵𝘢𝘨𝘪𝘰𝘯𝘦 0 della 𝘴𝘦𝘳𝘪𝘦 'Last Exile'. 🅴🆁🆁🅾🆁: list index out of range
> 
> ```
> Traceback (most recent call last):
>   File "/script/anime_downloader/__init__.py", line 23, in job
>     series = converting(raw_series)
>   File "/script/anime_downloader/functions.py", line 132, in converting
>     link = linkSearch(anime["title"], season["num"], anime["tvdbID"])
>   File "/script/anime_downloader/functions.py", line 59, in linkSearch
>     result = bindAnime(title, int(season), tvdbID)
>   File "/script/anime_downloader/functions.py", line 231, in bindAnime
>     "name": ret[season-1]["name"],
> IndexError: list index out of range
> ```
> 
> ### Descrizione [_Opzionale_]
> Il problema nasce quando su sonarr si seleziona la stagione "Specials" (gestita come stagione 0 da sonarr) e si ha l'auto ricerca link attiva.

FIX con la versione [1.7.3](https://github.com/MainKronos/Sonarr-AnimeDownloader/releases/tag/1.7.3)

**Comment by MainKronos** [comment]
> Credo che questo problema sia legato a quello sopra descritto
> 
> ## ![image](https://user-images.githubusercontent.com/25983005/162899195-07cfec87-402b-4e3e-b94c-e96b68a6e394.png)
> il link è https://www.animeworld.tv/play/ascendance-of-a-bookworm-3.l5fru
> 
> ![image](https://user-images.githubusercontent.com/25983005/162899273-e572e46e-26e7-46c4-8859-dab11a7ec24d.png)

Non sono sicuro sia correlato a questo errore, controlla se con la nuova versione ([1.7.3](https://github.com/MainKronos/Sonarr-AnimeDownloader/releases/tag/1.7.3)) si ripresenta

**Comment by berta24** [comment]
![image](https://user-images.githubusercontent.com/25983005/163329888-909e218f-9f7b-45b4-ac53-f87e06283a16.png)

Si, si ripresenta ancora anche con la 1.7.3

effettivamente è stato abbastanza strano il comportamento di sonarr, perché appena aggiunto l'anime era diviso in serie (0,1,2)
dove 0 era la prima stagione e così via.

Dopo l'errore vado a controllare e tutto l'anime è stato unificato in un unica prima stagione.
io ho provato tutte le combinazioni ma non funziona

**Comment by berta24** [comment]
Per completezza allego le prove.
Ecco come risulta la lista sulla tabella.

![image](https://user-images.githubusercontent.com/25983005/163345712-0ce83383-fa4b-4b99-a8a2-925b3d22c4b3.png)

---------------

Su sonarr infatti è un unica stagione da 38 episodi 
![image](https://user-images.githubusercontent.com/25983005/163346085-88c55700-170a-4686-b0d8-f7661ed0e98f.png)

**Comment by MainKronos** [comment]
Mi confermi che l'url di Sonarr che hai messo come variabile d'ambiente alla creazione del container è corretto?

Questo errore ti si presenta per un anime in particolare? Quando è comparso?

**Comment by berta24** [comment]
si l'url è corretto, tutti gli altri anime funzionano,
solo questo "Ascendance of a Bookworm" da problemi, mi ha scaricato tutte e 2 le prime stagioni, ma dal 27° episodio ossia la terza stagione, mi da questo errore, devo metterlo come absolute?

Si presenta da quando è uscita la serie a inizio aprile

**Comment by grievertime** [comment]
confermo che nel mio caso l'errore è risolto. Grazie!
