### ISSUE TITLE
ERRORE - file json

### ISSUE THREAD

**Issue by Simoneu01** [MainKronos/Sonarr-AnimeDownloader#49]
### Livello di Errore:
- `🅴🆁🆁🅾🆁`

### Messaggio di Errore
```python
🅴🆁🆁🅾🆁: Errore al file table.json.
Traceback (most recent call last):
  File "/script/anime_downloader/functions.py", line 114, in converting
    if len(list(row["seasons"][season["num"]])):
KeyError: '2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/script/anime_downloader/__init__.py", line 23, in job
    series = converting(raw_series)
  File "/script/anime_downloader/functions.py", line 142, in converting
    raise TableFormattingError
anime_downloader.exceptions.TableFormattingError: Errore al file table.json.
```

### Descrizione [_Opzionale_]
Non capisco dove sia il problema, il file non è stato mai modificato a mano quindi c'è qualche opzione che è andato a modificare in modo non corretto il file.

**Comment by MainKronos** [comment]
Prima di questo errore ti stampa `❌ La 𝘴𝘵𝘢𝘨𝘪𝘰𝘯𝘦 {season} della 𝘴𝘦𝘳𝘪𝘦 '{anime}' non esiste nella 𝗧𝗮𝗯𝗲𝗹𝗹𝗮 𝗗𝗶 𝗖𝗼𝗻𝘃𝗲𝗿𝘀𝗶𝗼𝗻𝗲.`?

**Comment by Simoneu01** [comment]
> Prima di questo errore ti stampa `❌ La 𝘴𝘵𝘢𝘨𝘪𝘰𝘯𝘦 {season} della 𝘴𝘦𝘳𝘪𝘦 '{anime}' non esiste nella 𝗧𝗮𝗯𝗲𝗹𝗹𝗮 𝗗𝗶 𝗖𝗼𝗻𝘃𝗲𝗿𝘀𝗶𝗼𝗻𝗲.`?

Si esce questo:
`❌ La 𝘴𝘵𝘢𝘨𝘪𝘰𝘯𝘦 2 della 𝘴𝘦𝘳𝘪𝘦 'Komi Can't Communicate' non esiste nella 𝗧𝗮𝗯𝗲𝗹𝗹𝗮 𝗗𝗶 𝗖𝗼𝗻𝘃𝗲𝗿𝘀𝗶𝗼𝗻𝗲.`

**Comment by MainKronos** [comment]
Dovrei aver già corretto l'errore, il fix si troverà nella prossima versione 👍

**Comment by MainKronos** [comment]
FIX con la versione [1.7.3](https://github.com/MainKronos/Sonarr-AnimeDownloader/releases/tag/1.7.3)
