### ISSUE TITLE
Sonarr in ambiente windows + info sul log

### ISSUE THREAD

**Issue by ManuJapan89** [MainKronos/Sonarr-AnimeDownloader#52]
HI, i'm having this issue
https://imgur.com/a/U5PKEws

could you help me? docker on windows 10
docker runned as admin

docker syntax used 
```cmd
docker run -d ^
  --name=Sonarr_AnimeWorld ^
  -v C:\Users\Manuel\Downloads\docker\files:/script/json/ ^
  -v C:\Users\Manuel\Downloads\docker\serie:/tv ^
  -v C:\Users\Manuel\Downloads\docker\downloadtemp:/Downloads ^
  -p 5000:5000 ^
  --env SONARR_URL='http://192.168.178.46:8989/' ^
  --env API_KEY='xxxxxxxxxxxxxxxxxxxxxxxxx' ^
  --env TZ=Europe/Rome ^
mainkronos/anime_downloader
```
thanks for any help

**Comment by ManuJapan89** [comment]
this is the error

https://cdn.discordapp.com/attachments/980197347600502806/991022564220477490/unknown.png

uso docker v4.9.1 WSL2

**Comment by MainKronos** [comment]
try with this:
```cmd
docker syntax used docker run -d 
  --name=Sonarr_AnimeWorld 
  -v C:\Users\Manuel\Downloads\docker\files:/script/json/ 
  -v C:\Users\Manuel\Downloads\docker\serie:/Users/Manuel/Downloads/docker/serie
  -v C:\Users\Manuel\Downloads\docker\downloadtemp:/Downloads 
  -p 5000:5000 
  --env SONARR_URL='http://192.168.178.46:8989/' 
  --env API_KEY='xxxxxxxxxxxxxxxxxxxxxxxxx' 
  --env TZ=Europe/Rome 
mainkronos/anime_downloader
```
I think the problem is that the folder structure inside the container and the folder structure that Sonarr uses are different.

Correlated #9

**Comment by ManuJapan89** [comment]
sono d'accordo. ho risolto
è normale che 
ho aggiunto questa serie a sonarr
![image](https://user-images.githubusercontent.com/82624098/176138715-52d3b782-c232-4197-92cd-28bcc9b8d19e.png)
e l'ho aggiunta al downloader 
![image](https://user-images.githubusercontent.com/82624098/176138814-f555a52a-22db-470f-8c7e-310f051eb55f.png)
ma nei log non ne vedo per niente traccia?
vedere log-->
https://pastebin.com/DMmx3q9M

cosa sbaglio?

detective conan zero's no tea time è nella stessa situa ma viene visto anche se dice, giustamente, non rilasciato

![image](https://user-images.githubusercontent.com/82624098/176139182-d4305d96-e903-411f-b01c-d8e24d5bb6af.png)

**Comment by MainKronos** [comment]
No, non hai fatto nulla di sbagliato
Il programma ricerca gli episodi solo quando sono usciti.
Ad esempio per `Detective Conan: Zero no Tea Time` su Sonarr gli episodi sono già tutti usciti, quindi il programma prova a cercarli su Animeworld, però sul sito l'intero anime non è ancora presente e quindi scrive nel log `⚠️ L'anime 'Detective Conan: Zero no Tea Time' non è acora disponibile.`
Se invece gli episodi di un anime come `Shine On! Bakumatsu Bad Boys!` non sono ancora usciti, cioè hanno una _Air Date_ futura, non vengono proprio ricercati e quindi non c'è traccia nel log.


<img width="500px" src="https://user-images.githubusercontent.com/21228689/176147926-dd254d70-c164-435f-8736-d00811ac5845.png" align="right">

Quindi, se un episodio non è ancora uscito su Sonarr, non viene ricercato, se è uscito ma l'anime non è disponibile su animeworld tipo così (img a destra) allora nel log troverai la scritta `⚠️ L'anime '{nome anime}' non è acora disponibile.`, se invece è anche disponibile ma l'episodio non è presente allora verrà scritto `✖️ L'episodio NON è ancora uscito.`
