### ISSUE TITLE
download di 1 episodio in modo errato

### ISSUE THREAD

**Issue by ManuJapan89** [MainKronos/Sonarr-AnimeDownloader#53]
### Informazioni generali
> _Compilare i campi_
* **Nome Anime**: RWBY: Ice Queendom
* **Stagione**: 1
* **Episodio**: 1
* **Link di AnimeWorld**: https://www.animeworld.tv/play/rwby-hyousetsu-teikoku.1K9Ul

l'episodio viene scaricato, ma me l'ha scaricato di 18 mega e rinominato al posto di 317 mega, come potete controllare dal direct download di animeworld.tv.

### Descrizione [_Opzionale_]
l'episodio viene scaricato, ma me l'ha scaricato di 18 mega e rinominato al posto di 317 mega, come potete controllare dal direct download di animeworld.tv. quindi su plex mi sono trovato una puntata 1. di 18 mega che dura 1 secondo e si blocca
succede spesso?

log pastebin https://pastebin.com/qHetrgwq

**Comment by MainKronos** [comment]
Di solito non accade, è molto strano...
Succede sempre solo con l'episodio 1 di RWBY: Ice Queendom?
Per tutti gli altri anime no?

**Comment by ManuJapan89** [comment]
ho risolto scaricando da RAD da uptobox, che tra l'altro mi sembrano gli stessi file
se vado a controllare la release di rad e quella di animeworld i file mi sembrano identici
in ogni caso non ce un modo di validare che un file sia stato scaricato corretto? o lato docker o lato sonarr intendo
non so dirti se ricapita. non ho riprovato ed è l'unica volta che mi è successo

**Comment by ManuJapan89** [comment]
ho provato a togliere l'episodio e spostarlo fuori plex/sonarr
riscaricarlo con il tool e dice questo

🔎 Ricerca anime 'RWBY: Ice Queendom' stagione 1.

🔎 Ricerca episodio 1.


⚙️ Verifica se l'episodio 𝐒1𝐄1 è disponibile.

✔️ L'episodio è disponibile.

⏳ Download episodio 𝐒1𝐄1.

⚠️ Errore di connessione. (HTTPSConnectionPool(host='server18.streamingaw.online', port=443): Max retries exceeded with url: /DDL/ANIME/RWBYHyousetsuTeikoku/RWBYHyousetsuTeikoku_Ep_01_SUB_ITA.mp4 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc668d322e0>: Failed to establish a new connection: [Errno 110] Connection timed out')))

**Comment by ManuJapan89** [comment]
se resetto la connessione non ci sono problemi.
domanda, non è possibile avere una barra completamento download stile jdownloader2? o almeno avere una vista dettagliata di quanto sta scaricando e se il file è integro. sarebbe molto utile :)

**Comment by MainKronos** [comment]
La barra di completamento è già stata implementata con la richiesta #38 
<img src="https://user-images.githubusercontent.com/21228689/159116844-df183bb1-2009-4bcb-b587-a49eea5daa87.png">

Si trova nella sezione Log nella pagina web, compare solo quando è in download un episodio

**Comment by ManuJapan89** [comment]
come la abilito? io non la vedo in basso nemmeno con download in corso
