### ISSUE TITLE
fix errore grammaticale :)

### ISSUE THREAD

**Issue by ManuJapan89** [MainKronos/Sonarr-AnimeDownloader#57]
quando un anime non è disponibile non scrive "ancora" ma acora :) 
 L'anime 'Bastard!! Ankoku no Hakaishin' non è acora disponibile.

è una cavolata ;) ma te lo riporto

Un lavoro grandissimo. grazie anocra

**Comment by berta24** [comment]
![image](https://user-images.githubusercontent.com/25983005/176705740-54511181-0f89-44d8-8bfb-23b3dc4598b5.png)

vedendo il codice mi sembra corretto

**Comment by ManuJapan89** [comment]
Non escludo che il problema sia mio :) 
![Screenshot_20220630_202312_com microsoft emmx](https://user-images.githubusercontent.com/82624098/176750539-8c3e524c-75f8-4699-928b-cbcb595d2b2b.jpg)
Allego evidenza

**Comment by MainKronos** [comment]
Si, grazie mille, hai fatto bene a segnalarlo. Probabilmente è un errore di stanchezza visto che lavoro a questo progetto principalmente di notte 😅. Correggo subito l'errore 👍
P.S L'errore deriva dalla libreria [AnimeWorld-API](https://github.com/MainKronos/AnimeWorld-API) e a quanto pare questa svista c'è da più di un anno e nessuno se ne è accorto 😂

**Comment by ManuJapan89** [comment]
Guarda, il vostro progetto mi leva ore e ore di lavoro manuale. scarico 50 serie a stagione. ho una libreria immensa.
vi dovrebbero fare un monumento. mi spiaceva quasi rompere i coglioni ma sono uno spaccapalle di professione :D 
capisco le difficoltà perchè ahimè lavoro nell'IT

**Comment by MainKronos** [comment]
Risolto con la [`1.8.1`](https://github.com/MainKronos/Sonarr-AnimeDownloader/releases/tag/1.8.1)
