### ISSUE TITLE
docker vhdx con solo container Sonarr-Animedownloader molto grande

### ISSUE THREAD

**Issue by ManuJapan89** [MainKronos/Sonarr-AnimeDownloader#58]
Credevo di aver risolto rifacendo il container con meno specifiche lato docker resources ma invece no
Appena creato il container occupava, il vhdx 900 mega
stamattina controllo 11 GB
alcuni screen:
cli del docker container
![image](https://user-images.githubusercontent.com/82624098/176854996-a9e95ccf-297a-4a04-96dd-4acd77342d45.png)

advanced resourced di Docker
![image](https://user-images.githubusercontent.com/82624098/176855134-d848b567-f34c-4eae-95f0-fc14f72415fb.png)

container presenti(solo il vostro)
![image](https://user-images.githubusercontent.com/82624098/176855236-738e0d91-e249-4f63-adcf-1c1218b37703.png)

docker in modalità hyper-v

file vhdx
![image](https://user-images.githubusercontent.com/82624098/176855636-46eecd29-2828-4da7-90d2-10584ae254d2.png)

mi confermate che è un comportamento normale? anche se dubito sia colpa del container

il comando da me utilizzato per creare il container, al netto delle sonarr api key è il seguente:

Pull : docker pull mainkronos/anime_downloader

comando in powershell admin:
docker run -d --name=Sonarr_AnimeWorld -v W:\Docker\files:/script/json/ -v Z:\Aniplex:/Aniplex  -v Z:\Download:/Downloads -p 5000:5000 --env SONARR_URL='http://192.168.178.44:8989/' --env API_KEY='******************************** --env TZ=Europe/Rome mainkronos/anime_downloader

Se mi confermate che è tutto ok lascio stare ;)

**Comment by berta24** [comment]
l'unica dubbio che mi viene in mente è che i video scaricati non vengano spostati ma restino salvati nel docker, controlla quanta roba hai scaricato e quanto pesa, vedi se le dimensioni combaciano

**Comment by ManuJapan89** [comment]
sarebbe un bel problema

**Comment by berta24** [comment]
non so come funzioni docker desktop, ma su Unraid i docker sono gestiti in modo da utilizzare lo spazio che gli serve indefinitamente,

![image](https://user-images.githubusercontent.com/25983005/176858465-b546fc47-42fe-46d4-8a8f-bdceb330b1e5.png)

In questo caso i file sono tutti all'interno della cartella docker /tv , e la cartella del docker viene montata in un altra cartella sull'host.

**Comment by ManuJapan89** [comment]
ma se sposto vhdx da disco c a un altro disco esterno? succede qualcosa?

**Comment by berta24** [comment]
se nelle impostazioni di docker c'è la possibilità di cambiare dove vengono salvati i file vhdx puoi farlo, altrimenti penso te lo ricrei da capo nella posizione originaria

**Comment by ManuJapan89** [comment]
non riesco ad esplorare il vhdx,vorrei capire cosa ce dentro cavolo

**Comment by ManuJapan89** [comment]
copio il vhdx su un altra macchina winzoz e provo a montarla. vedo cosa cacchio occupa 11 GB

**Comment by berta24** [comment]
il file vhdx è il docker vero e proprio, scusa ma se entri in docker desktop 
![image](https://user-images.githubusercontent.com/25983005/176861006-6645f057-e363-4ac4-b596-96d7aa691acc.png)

Apri il terminale del docker puoi vedere cosa c'è dentro, non devi aprire letteralmente il file

**Comment by berta24** [comment]
fammi un cd .. fino alla cartella principale poi ls

**Comment by berta24** [comment]
"cd .." il comando è anche con i punti

**Comment by ManuJapan89** [comment]
![image](https://user-images.githubusercontent.com/82624098/176863908-7de30e81-dc4c-47bb-a274-2b26bad3d08e.png)

**Comment by berta24** [comment]
ls aniplex

ls Downloads

**Comment by ManuJapan89** [comment]
![image](https://user-images.githubusercontent.com/82624098/176865469-19971418-a09a-484c-a66d-eb62fdc12c6b.png)
ls aniplex è la cartella finale dove prima che usavo docker, mettevo già gli anime x plex rinominati
è immensa. 300+ cartelle. tera su tera
ls Downloads l'ho usata come directory temp del docker ma effettivamente è la cartella temporanea di download che usavo prima con jdownloader2 e effettivamente ora ha 17 GB usati
immagino che sia meglio che con jd2 se devo scaricare roba uso un altra cartella giusto?

**Comment by berta24** [comment]
Vediamo cosa dice MainKronos, ma secondo me è un comportamento normale del docker alla fine...

![image](https://user-images.githubusercontent.com/25983005/176867092-1b70fa09-3f01-4d86-ab56-9d30a8eb7658.png)

Anche il mio occupa circa 32 gb

**Comment by ManuJapan89** [comment]
vediamo :) ma se io ho messo massimo disco 16 GB...  cosa succede se gliene serve di piu?

**Comment by MainKronos** [comment]
Scusatemi ma non ho capito qual è il problema. Il problema è che il filesystem `overlay` è grande? O il problema è nei volumi?

**Comment by ManuJapan89** [comment]
Ciao @MainKronos
Il problema è che il file vhdx di docker passa, in 2 giorni da 900MB a 11 GB. Con limite impostato a 16 GB nelle risorse.
Mi chiedevo se era normale

**Comment by ManuJapan89** [comment]
@MainKronos inoltre la cartella download che ho dato al docker... Dove teoricamente scarica la roba prima di spostare se non ho capito male... In passato la usavo con JDownloader 2 e non è vuota... A volte la uso ancora. È per questo che il file vhdx si allarga?

**Comment by MainKronos** [comment]
Si, secondo me è normale

**Comment by ManuJapan89** [comment]
chiaro
![image](https://user-images.githubusercontent.com/82624098/176999864-37f36a7b-b0ad-4ab6-bb9e-d278d939239e.png)
ho ridotto le risorse al minimo. se mi confermi che sono sufficienti per il tuo programma, poi possiamo chiudere anche questo issue :)

**Comment by MainKronos** [comment]
Si, dovrebbe essere sufficiente.
Il massimo spazio che può occupare è quello di un episodio di 20 minuti a qualità 720p.

**Comment by ManuJapan89** [comment]
assolutamente perfetto :) puoi chiudere ^^
