### ISSUE TITLE
Libreria animeworld

### ISSUE THREAD

**Issue by MainKronos** [MainKronos/Sonarr-AnimeDownloader#6]
La libreria si trova su [PYPI](https://pypi.org/project/animeworld/).

Libreria: [AnimeWorld-API](https://github.com/MainKronos/AnimeWorld-API)

**Comment by Solang99** [comment]
Ciao, sarebbe possibile dare un occhio al sorgente?

**Comment by MainKronos** [comment]
mhhh, a quanto pare non posso dare un accesso con permessi di sola lettura al repository....
Quindi l'ho rimesso ad accesso pubblico 😂

Spero che quelli di AnimeWorld non lo scoprino

Il link è questo: https://github.com/MainKronos/AnimeWorld-API

**Comment by Solang99** [comment]
Graize mille, gli daro un occhiata.
Ps:Complimenti hai fatto un attimo lavoro

**Comment by MainKronos** [comment]
Libreria: [AnimeWorld-API](../tree/main/documentation/library)
Password: `ItCanBeBetter`

**Comment by MainKronos** [comment]
Aggiunta una wiki più accessibile.
Può essere trovata [qui](../wiki)

**Comment by AnimeWorldtv** [comment]
> mhhh, a quanto pare non posso dare un accesso con permessi di sola lettura al repository.... Quindi l'ho rimesso ad accesso pubblico 😂
> 
> Spero che quelli di AnimeWorld non lo scoprino
> 
> Il link è questo: https://github.com/MainKronos/AnimeWorld-API

"Spero che quelli di AnimeWorld non lo scoprino" per chi ci hai preso? teniamo monitorate anche le request che vengono fatte al sito, e come te sappiamo anche le altre APP che ci fanno web scraping.

Ti abbiamo già riferito in passato di non usare questo metodo perché se tu leggessi le faq del sito, sapresti anche che è contro il nostro TOS il web scraping in quanto ci causa carichi inutili. 

Quello che da più fastidio sono le persone come te che d'altronde non è tanto il web scraping ma il fatto che noi non ci guadagniamo niente e abbiamo oltre 80 server nel sito da pagare, di certo non le paghiamo non mostrando ADS e scaricando in modo abusivo dalla tua "API" (Che poi, chiamarla api è un po' esagerato.) "se solo avessi accesso alle loro api interne non sarei costretto a bombardargli il sito" l'accesso alle api è presente qui da tempo: https://api.animeworld.tv basta richiederle, OVVIAMENTE non avrai l'acceso ai server ma solo alle info anime come giusto che sia, a cosa servirebbero gli ADS? 

Detto questo, ti chiediamo gentilmente di non usare web scraping in quanto in violazione con il nostro TOS. potevi benissimo contattare noi prima di intraprendere alcune azioni, invece hai continuato a fare cose illecite.

Grazie e Cordiali Saluti
Team Tecnico AnimeWorld

**Comment by MainKronos** [comment]
Io vi ho scritto molte email e ho parlato anche con il vostro sviluppatore ██████████, una persona molto gentile e comprensiva.
Ho avuto modo di provare le vostre websockets "API" ho anche sviluppata dei wrapper per migliorare l'uso visto che non esistevano librerie in python, ma come ben saprete queste API sono praticamente paragonabili ad un feed RSS, quindi praticamente inutili.

Quindi fino ad oggi, e solo per cortesia a ██████████, avevo mantenuto la libreria privata; era zippata ma con password solo per correttezza perchè un codice open source deve essere sempre accessibile a chiunque.

Oltretutto trovo molto brutto venirmi a scrivere qui pubblicamente che faccio cose ILLECETE quando vuoi rubate ogni tipo di contenuto a chiunque senza dargli i loro crediti e meriti, ho fatto parte e tuttora faccio parte di gruppi che traducono GRATUITAMENTE anime e manga a disposizione di tutti e voi avete addirittura il coraggio di dirmi che non riuscite a pagare i vostri 80 server, mentre noi è già una grande soddisfazione se riceviamo 2 spiccioli di supporto solo per incoraggiarci a continuare. 

Personalmente del vostro TOS me ne frega il giusto come a voi frega della fatica e dell'impegno degli altri.

Fino ad ora ho durato una fatica immane a cercare di sviluppare questa mia libreria da SOLO prestando sempre molta attenzione a limitare il più possibile richieste inutili ai vostri sever.

Vorrei inoltre precisare che questa libreria l'ho creata solamente per riuscire a vedere gli anime stagionali, senza ogni volta doverli per forza scaricare manualmente. Quindi se solo voi foste stati un po' più flessibili queste "API" non sarebbero mai esistita.

Dopo aver letto il vostro messaggio ritengo inutile a questo punto mantenere la mia libreria privata, quindi da ora in poi rimarrà pubblica e farò di tutto affinché più persone vi contribuiscano.

Cordiali Saluti,
lo sviluppatore che non sopportate
