### ISSUE TITLE
overlord 4 non compare nei log

### ISSUE THREAD

**Issue by ManuJapan89** [MainKronos/Sonarr-AnimeDownloader#61]
Ciao, Overlord 4 --> https://www.animeworld.tv/play/overlord-4.u74oI/tba
non compare nei log 
[log (1).log](https://github.com/MainKronos/Sonarr-AnimeDownloader/files/9046648/log.1.log)
screen dettagliati:

![image](https://user-images.githubusercontent.com/82624098/177337490-44b2791f-d2c1-48cd-a57f-5c135b8722bb.png)

![image](https://user-images.githubusercontent.com/82624098/177337533-1b8cbee9-b708-483e-bddc-f8a2fe676e53.png)

![image](https://user-images.githubusercontent.com/82624098/177337632-2f717a56-84fe-4e00-a441-b85c2e97f47c.png)

stò sbagliando qualcosa io?
ho già restartato piu volte il docker, dopo un refresh series di sonarr.
Grazie

**Comment by berta24** [comment]
Bhe non è ancora uscito ed è ancora in TBA quindi è normale...

**Comment by ManuJapan89** [comment]
anche dropkick on my devil lo è, non ancora uscito su AW ma per sonarr si
![image](https://user-images.githubusercontent.com/82624098/177340940-87691566-04e8-49ee-8d98-3645ddc1d0da.png)

![image](https://user-images.githubusercontent.com/82624098/177340773-e53db243-1056-4e59-8768-db21dd27d2ae.png)

ma nei log compare. come appunto non ancora disponibile
come mai overlord stagione 4 no?
![image](https://user-images.githubusercontent.com/82624098/177340893-0654715b-03bf-4772-9393-7d87f73590cc.png)
Confermi che ho settato giusto?

**Comment by ManuJapan89** [comment]
si dopo un ora è andata
