### ISSUE TITLE
1.8.1 download bar is missing

### ISSUE THREAD

**Issue by ManuJapan89** [MainKronos/Sonarr-AnimeDownloader#65]
ciao, nella 1.8.1 non mi compare la download bar sotto nella sezione log. solo a me? è da attivare?

**Comment by MainKronos** [comment]
stranamente non funzionava più socketio...
dovrei aver corretto, alla prossima release dovrebbe funzionare tutto come prima

**Comment by ManuJapan89** [comment]
perfetto :) scusatemi. sono un vero spaccapalle :(
