### ISSUE TITLE
anime non si scarica e non compare nei log

### ISSUE THREAD

**Issue by ManuJapan89** [MainKronos/Sonarr-AnimeDownloader#66]
ciao,
ho aggiornato all'ultima versione che ha corretto la barra di download
ho tentato di aggiungere natsu no arashi! 2
![image](https://user-images.githubusercontent.com/82624098/179393605-058402cf-12a2-4f62-9abc-e491a30f93c6.png)
![image](https://user-images.githubusercontent.com/82624098/179393617-aed76efb-f9a6-4d16-a7ce-28965b689551.png)
![image](https://user-images.githubusercontent.com/82624098/179393629-cd623d86-6b24-4b75-b603-5153730f5542.png)
![image](https://user-images.githubusercontent.com/82624098/179393636-b288b4d1-5845-43b0-86f5-d888493913cb.png)

il link su animeworld è questo
https://www.animeworld.tv/play/natsu-no-arashi-2.HXSmf/dRXFT

tolto tutto dopo la barra, riavviato piu volte
non compare nemmeno nei log.
[log (3).log](https://github.com/MainKronos/Sonarr-AnimeDownloader/files/9127408/log.3.log)
ecco il log :)
Sbaglio qualcosa?

**Comment by ManuJapan89** [comment]
in realtà sembra non andare neanche nelle vecchie versioni :) Grazie per l'aiuto in anticipo

**Comment by ManuJapan89** [comment]
ho provato un altro anime 
esempio https://www.animeworld.tv/play/hit-o-nerae.UYDaw/Mkv0l
e va

**Comment by MainKronos** [comment]
Noto dall'immagine dell'anime su sonarr che il conteggio degli episodi monitorati della seconda stagione è `0/0`, ha controllato se gli episodi sono effettivamente monitorati?

**Comment by ManuJapan89** [comment]
è una serie nuova che gli ho chiesto di scaricare. da 0.ma avendo la prima stagione in un altro disco gli ho chiesto a sonarr di scaricare solo lastest season. ma facendo cosi mi ha messo 0/0. se metto missing episodes scarica la seconda e mi dice giustamente che la 1a serie non ce in tabella di conversione.
ho sempre fatto cosi per le seconde stagioni senza problemi :D boh

**Comment by MainKronos** [comment]
Quindi il problema è risolto 😆?

**Comment by ManuJapan89** [comment]
si ma non capisco come mai sonarr mi mette 0/0 se gli chiedo monitora last season e natsu no arashi ha 2 stagioni. è un bug loro secondo te?

**Comment by MainKronos** [comment]
Forse perchè è un anime vecchio, no so... Comunque si, è un problema di Sonarr

**Comment by MainKronos** [comment]
Correlato #46
