### ISSUE TITLE
Urgente : Il sito è cambiato, di conseguenza la libreria è DEPRECATA. 

### ISSUE THREAD

**Issue by ManuJapan89** [MainKronos/Sonarr-AnimeDownloader#67]
Ciao, ti segnalo che è capitato questo errore :) riesci a sistemare? Thanks :)
in allegato i log ;)

🔎 Ricerca anime 'Vermeil in Gold' stagione 1.
🔎 Ricerca episodio 3.
🅰🅻🅴🆁🆃: Il sito è cambiato, di conseguenza la libreria è DEPRECATA. -> [File /usr/local/lib/python3.9/site-packages/animeworld/utility.py in fixCookie - 42]
[log (4).log](https://github.com/MainKronos/Sonarr-AnimeDownloader/files/9142416/log.4.log)

**Comment by berta24** [comment]
Duplicato di #21
