### ISSUE TITLE
ERROR: RTMP download detected but "rtmpdump" could not be run

### ISSUE THREAD

**Issue by grievertime** [MainKronos/Sonarr-AnimeDownloader#69]
### Informazioni generali
* **Nome Anime**:  Tokyo Ghoul
* **Stagione**:  1
* **Episodio**:  1
* **Link di AnimeWorld**:  https://www.animeworld.tv/play/tokyo-ghoul.uONT4/Ha920

### Livello di Errore:
- `🅴🆁🆁🅾🆁`

### Messaggio di Errore
🅴🆁🆁🅾🆁: ERROR: RTMP download detected but "rtmpdump" could not be run. Please install it.

### Descrizione [_Opzionale_]
youtube_dl.utils.DownloadError: ERROR: RTMP download detected but "rtmpdump" could not be run. Please install it.

**Comment by MainKronos** [comment]
Presumo sia un problema della libreria `yutube-dl` perchè anche installando `rtmpdump` solleva un errore.

Probabilmente hanno fato modifiche al sito di VVVVID e la libreria è rimasta indietro. Continuo a cercare una soluzione, se avete idee o informazioni scrivete qui sotto

**Comment by MainKronos** [comment]
VVVVID ormai non detiene più anime _esclusivi_, quindi il supporto di VVVVID (della libreria [AnimeWorld-API](https://github.com/MainKronos/AnimeWorld-API)) è stato rimosso.
