### ISSUE TITLE
chiarimento aggiunta più mountpoint windows 10

### ISSUE THREAD

**Issue by ManuJapan89** [MainKronos/Sonarr-AnimeDownloader#70]
Ciao, vorrei un chiarimento siccome in futuro dovrò aggiungere un nuovo mountpoint a quello attuale

il mio attuale comando del docker è questo
```cmd
docker run -d ^
  --name=Sonarr_AnimeWorld ^
  -v W:\Docker\files:/script/json/ ^
  -v Z:\Aniplex:/Aniplex ^
  -v Z:\Download:/Downloads ^
  -p 5000:5000 ^
  --env SONARR_URL='http://192.168.178.44:8989/' ^
  --env API_KEY='xxxxxxxxxxxxxxxxxxxxxxxxx' ^
  --env TZ=Europe/Rome ^
mainkronos/anime_downloader
```

ora io scarico tutti gli anime in Z:\Aniplex
ipotizziamo che poi aggiungo un disco su lettera V:
e il percorso è V:\Aniplex2

Lato Sonarr, immagino che devo aggiungere il percorso nuovo come root folders
qui
![image](https://user-images.githubusercontent.com/82624098/182334383-4b2b19ab-081a-4a36-933e-6d9311b43ad2.png)

corretto?

Lato docker è corretto invece questo nuovo comando?:
```cmd
docker run -d ^
  --name=Sonarr_AnimeWorld ^
  -v W:\Docker\files:/script/json/ ^
  -v Z:\Aniplex:/Aniplex ^
  -v V:\Aniplex2:/Aniplex2 ^
  -v Z:\Download:/Downloads ^
  -p 5000:5000 ^
  --env SONARR_URL='http://192.168.178.44:8989/' ^
  --env API_KEY='xxxxxxxxxxxxxxxxxxxxxxxxxxxx' ^
  --env TZ=Europe/Rome ^
mainkronos/anime_downloader  
```
ovviamente poi lato docker và aggiunta la nuova path alle shared resourced
![image](https://user-images.githubusercontent.com/82624098/182335213-881645c7-fb04-4006-8db3-30787a9982f1.png)

in questo modo.

è tutto corretto o ho preso una cantonata?

infine quando aggiungi una nuova serie, esempio:
![image](https://user-images.githubusercontent.com/82624098/182335486-fb5be96d-c67a-4fcc-b33a-5a670d618b99.png)

selezioni nel root folder field il nuovo percorso, e il programma insieme a Sonarr mi metterà i nuovi anime li.

Vi ringrazio in anticipo per il riscontro :)

**Comment by MainKronos** [comment]
Si, tutto corretto!
Per non sbagliarsi mai basta ricordarsi che la struttura interna delle cartelle del container di Sonarr deve coincide alla struttura interna del container di `mainkronos/anime_downloader` 👍

**Comment by ManuJapan89** [comment]
si in realtà io non ho sonarr in container ma come programma ma ho capito il punto :)
