### ISSUE TITLE
tekken bloodline non ha numerazione assoluta

### ISSUE THREAD

**Issue by ManuJapan89** [MainKronos/Sonarr-AnimeDownloader#71]
Ciao,
come potete vedere dall'immagine tekken non ha numerazione assoluta e quindi non viene scaricato
![image](https://user-images.githubusercontent.com/82624098/185751592-f392b08c-2d00-4977-b7fc-df0ee362ffe5.png)

ho postato la cosa sul subreddit di sonarr 
https://www.reddit.com/r/sonarr/comments/wt2gix/tekken_bloodline_episodes_doesnt_have_absolute/
e mi hanno risposto che potenzialmente non l'avrà mai. e di mettere come series type altro e non anime. ma cosi il programma non va o sbaglio?

anche questa è una serie netflix ma non ho avuto problemi

![image](https://user-images.githubusercontent.com/82624098/185751739-c7d87d7b-079f-4961-9308-c5b3918f7e1f.png)
![image](https://user-images.githubusercontent.com/82624098/185751742-8d4e3439-e5fb-4a24-abf4-1735b860d488.png)

avete consigli?

**Comment by MainKronos** [comment]
Deve essere aggiornata la pagina di `[the TVDB](https://thetvdb.com/series/tekken-bloodline)` relativa all'anime, aggiungendoci la numerazione assoluta

**Comment by MainKronos** [comment]
Duplicate of #33
