### ISSUE TITLE
Uncle from another world - problema ricorrente

### ISSUE THREAD

**Issue by ManuJapan89** [MainKronos/Sonarr-AnimeDownloader#72]
Buongiorno,
di tanto in tanto questa serie smette di essere scaricata
e nei log compare questo
![image](https://user-images.githubusercontent.com/82624098/186606488-c7e10ff9-1cdd-4b5f-ac41-d6614a194ebe.png)
❌ La 𝘴𝘦𝘳𝘪𝘦 'Uncle From Another World' non esiste nella 𝗧𝗮𝗯𝗲𝗹𝗹𝗮 𝗗𝗶 𝗖𝗼𝗻𝘃𝗲𝗿𝘀𝗶𝗼𝗻𝗲.
ma la serie esiste e ha i valori corretti
![image](https://user-images.githubusercontent.com/82624098/186606665-08a999a9-c164-4784-8cc7-674ededd62b5.png)

solitamente, togliendola e rimettendola risolve il problema temporaneamente

ecco le info su sonarr, i settings

![image](https://user-images.githubusercontent.com/82624098/186606847-6728d8f8-c2d0-4ae6-93e8-e0ff87122b84.png)

avete idee?

Grazie Mille

**Comment by MainKronos** [comment]
Scusami se ti rispondo un po' in ritardo ma sono in vacanza 😅
Mi è capitato anche a me un problema simile, molto probabilmente è causato dalle informazioni riguardanti il nome dell'anime di TvDB che vengono modificate. Certe volte modificano una lettera minuscola in maiuscola o rimuovono una virgola, etc...
Visto che la corrispondenza viene fatta tramite il nome, se c'è una variazione non c'è più il match.

**Comment by ManuJapan89** [comment]
ah capisco.
basta che si decidono. è la 3a volta che lo rifaccio. per ripicca non lo vedo. mi sta sul cazzo già
