### ISSUE TITLE
Cannot start - Fresh install 

### ISSUE THREAD

**Issue by berta24** [MainKronos/Sonarr-AnimeDownloader#74]
Credo sia un problema mio, ma non riesco più a startarlo:
![image](https://user-images.githubusercontent.com/25983005/192455144-db431c0e-0f5f-4b1b-89cb-a7949302c48e.png)

Ho configurato un pc nuovo e quando lo faccio partire mi dice questo...
Ho provato sia a cambiare l'owner della cartella che a startarlo come admin,
Cosa altro posso provare?

ho scaricato la latest version, quindi è aggiornato

**Comment by berta24** [comment]
mmmh abbastanza strano, ho risolto non specificando la cartella script nel docker run, è normale?

**Comment by MainKronos** [comment]
Dal codice di errore ti posso dire che il programma legge un file json, probabilmente settings.json, il cui contenuto è None (file vuoto)
Faccio dei controlli

**Comment by MainKronos** [comment]
Mi puoi allegare il tuo docker run/compose ?

**Comment by berta24** [comment]
Si ho notato anche io, mi copia settings e table.json vuoti. li ho riempiti e funziona.
L'unico problema è che non mi va più il connections...
Adesso ti allego tutto

**Comment by berta24** [comment]
![image](https://user-images.githubusercontent.com/25983005/192609912-f5ba061a-10c1-48fc-9807-287bc2d05987.png)

Io uso Unraid e ho tutte le variabili specificate, ho provato anche con il comando ma il risultato era lo stesso (i valori erano uguali)

![image](https://user-images.githubusercontent.com/25983005/192610070-a6df4f5a-99b6-49cc-bb94-cea7aa12a33d.png)
lui mi dice che trova il file telegram.sh, ma quando lo abilito va in errore
![image](https://user-images.githubusercontent.com/25983005/192610151-bbb4a415-dce2-403c-a5a9-20ab185e2d6e.png)

![image](https://user-images.githubusercontent.com/25983005/192610206-6538adf9-2d5e-4079-8981-68b8fbca53a2.png)

**Comment by MainKronos** [comment]
Per l'ultimo problema riguardante le connection guarda qui #64, è il classico problema di quando si creano i file in ambient windows e si eseguono su linux

**Comment by berta24** [comment]
![image](https://user-images.githubusercontent.com/25983005/192614376-795882b8-1578-4677-b6a8-1009dd61bca7.png)

Con questo docker run che è la copia dell'altro funzionante tranne per il path dei json
![image](https://user-images.githubusercontent.com/25983005/192614455-a49cab36-5543-43cb-bd25-95a9ac5e10a7.png)
![image](https://user-images.githubusercontent.com/25983005/192614571-73faa1ef-6234-4bec-ae14-3bc13791e655.png)

I file sono vuoti e creati con l'utente  1000-1000

**Comment by MainKronos** [comment]
Ho capito qual è il problema. Il problema è che i file vengono creati vuoti all'inizio del programma ([qui](https://github.com/MainKronos/Sonarr-AnimeDownloader/blob/main/config/start.sh#L21L22)) se non esistono, ma non ci viene scritto niente. Quando poi vengono fatti i controlli successivi non si accorgono del problema, perchè avevo assunto che se il file fosse esistito, sicuramente la struttura interna sarebbe stata consistente.
Farò una correzione quanto prima, nel mentre sostituisci i file vuoti con questi: [`table.json`](https://github.com/MainKronos/Sonarr-AnimeDownloader/blob/main/documentation/examples/json/table.json), [`settings.json`](https://github.com/MainKronos/Sonarr-AnimeDownloader/blob/main/documentation/examples/json/settings.json)

**Comment by berta24** [comment]
sisi è quello che ho fatto attualmente, strano che le persone che l'hanno installato qui ultimamente non abbiano detto nulla

**Comment by MainKronos** [comment]
Dovrei aver corretto il problema, la correzione sarà per adesso in **_dev_** e poi passerà in **_latest_**.
Se la vuoi provare usa `ghcr.io/mainkronos/anime_downloader:dev`
