### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by berta24** [MainKronos/Sonarr-AnimeDownloader#79]
Ciao, ho fatto l’update oggi alla latest version e mi da problemi con i download, allego screen di prova 
![359A4F53-EC67-4083-AD37-34160BFA59F9](https://user-images.githubusercontent.com/25983005/195452638-34c7758f-ce2f-4cca-b8e7-3da731333279.png)

**Comment by MainKronos** [comment]
Quell'errore si verifica perché la libreria animeworld non e aggiornata. E molto strano....
Prova a riavviare il container o aggiorna forzatamente la libreria con  `pip install -U animeworld`
(L'ultima versione della libreria e la 1.4.20)

**Comment by berta24** [comment]
![image](https://user-images.githubusercontent.com/25983005/195544622-bafb07bd-ae27-4a41-b397-30f9cc97c81a.png)
la libreria era già aggiornata, ho forzato l'update del container, mi ha riscaricato tutto ed ora funziona
