### ISSUE TITLE
INFO: Upgrade In-place a windows 11

### ISSUE THREAD

**Issue by ManuJapan89** [MainKronos/Sonarr-AnimeDownloader#83]
Ciao, 
vorrei fare un update inplace da windows 10 a windows 11
prevedi qualche incompatibilità o vado liscio?
in docker non uso la wsl ma hyper-v

Grazie mille per un riscontro :)

**Comment by MainKronos** [comment]
Non ci dovrebbero essere problemi. E questo il bello di cocker, tutto il sistema è virtualizzato.
Non dovrebbero esserci problemi nemmeno nel caso tu volessi passare da Windows ad una distribuzione linux
Quindi vai tranquillo, nel caso di problemi apri un issue 👍
