### ISSUE TITLE
[BUG] Connection aborted

### ISSUE THREAD

**Issue by ManuJapan89** [MainKronos/Sonarr-AnimeDownloader#86]
Ciao,
io ho spesso questo errore negli ultimi giorni

🔎 Ricerca anime 'Yu-Gi-Oh!: Sevens' stagione 1.
⚠️ Errore di connessione. (('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))

ora controllerò link ecc ecc. è un errore della connessione inteso, che mi blocca il mio ip ecc ecc?

**Comment by MainKronos** [comment]
- Quanto spesso accade? Ad ogni ciclo di ricerca? Ogni giorno? Ad un orario specifico? Solo di giorno o di notte?
- Accade per un anime specifico?
- Accade solo in fase di ricerca? Accade anche in altre fasi, tipo quella di download?

**Comment by ManuJapan89** [comment]
Ciao,
Succede a ogni ricerca da almeno una settimana quindi ogni 30 minuti
Mi pare solo su quell’anime o pochi altri
Quello di yugi sevens sicuro
Il link è corretto nella tabella
Già verificato
Una cosa strana,ho già tutti gli episodi
74 sono disponibili e ne ho 74
Verificato la disponibilità da Sonarr

Grazie mille


Il giorno mer 16 nov 2022 alle 16:24 Krónos ***@***.***> ha
scritto:

**Comment by MainKronos** [comment]
mi puoi inviare il log completo?
Premi il pulsante in fondo alla pagina del log e inviami il file. (Il file generato ha già offuscate le informazioni private)
![Immagine 2022-11-08 193338](https://user-images.githubusercontent.com/21228689/200647064-5cf1dc4f-d2fa-4532-8308-2421f7e16dea.png)

**Comment by ManuJapan89** [comment]
Certamente.te lo allego
[image: File di testo]
log.log.txt
<https://drive.google.com/file/d/1kPgJ_k_e0rGEJF-4YA9yxOVc4GPQqChE/view?usp=drivesdk>

Il giorno gio 17 nov 2022 alle 12:01 Krónos ***@***.***> ha
scritto:

**Comment by MainKronos** [comment]
Non ho accesso al file 😅.
Caricalo direttamente qui su GitHub come messaggio, trascinalo nel box dove scrivi il testo.

**Comment by ManuJapan89** [comment]
[log.log.txt](https://github.com/MainKronos/Sonarr-AnimeDownloader/files/10033017/log.log.txt)
eccolo @MainKronos thanks

**Comment by MainKronos** [comment]
Non sono riuscito a replicare il problema, potrebbe essere un errore della tua rete causato da una scarsa qualità del segnale. Se qualcun altro ha lo stesso problema lo scriva qui sotto.
