### ISSUE TITLE
file table .json cancellato

### ISSUE THREAD

**Issue by ManuJapan89** [MainKronos/Sonarr-AnimeDownloader#87]
Ciao, durante l'aggiunta di una serie mi si è completamente cancellato il file table.json lasciandomi solo l'ultima appena inserita
vi prego ditemi che si può recuperare in qualche modo o me lo devo rifare a mano tutto. saranno 200 serie inserite :(

**Comment by MainKronos** [comment]
Prova ad eseguire questo comando sostituendo `<container_name>` con il nome che hai dato al container (di default è `AnimeDownloader`) e inviami l'output:
```cmd
docker exec <container_name> /bin/bash -c "find /script -name *.json -printf '%c %p\n\r'" -d
```

**Comment by ManuJapan89** [comment]
ormai l'ho rifatto :D ma te lo faccio
di 124 serie inserite all'inizio ne ho dovute reinserire 50
non benissimo

**Comment by ManuJapan89** [comment]
> nimeDownloader

![image](https://user-images.githubusercontent.com/82624098/205379225-0a55217b-b959-4400-8abb-ab930f29cff7.png)

**Comment by MainKronos** [comment]
Mi dispiace ma devi reinserirle a mano 😓
Se vuoi c'è il file di esempio con un po' di serie già configurate: [table.json](https://github.com/MainKronos/Sonarr-AnimeDownloader/blob/main/documentation/examples/json/table.json)

**Comment by ManuJapan89** [comment]
> Mi dispiace ma devi reinserirle a mano 😓 Se vuoi c'è il file di esempio con un po' di serie già configurate: [table.json](https://github.com/MainKronos/Sonarr-AnimeDownloader/blob/main/documentation/examples/json/table.json)

no problem in un oretta abbondante le ho rifatte. escludendo le serie verdi su sonarr da 124 sono arrivato a 50
devo comunque fare un backup di sto file. è critico

**Comment by MainKronos** [comment]
![Immagine 2022-12-02 212811](https://user-images.githubusercontent.com/21228689/205380157-4c5b8336-b3ab-4f6d-ad61-c405f671ec04.png)

per facilitare l'operazione di backup tutte le "parti critiche" hanno un pulsante per scaricare (blu) e per caricare (verde) le proprie configurazioni

**Comment by ManuJapan89** [comment]
> ![Immagine 2022-12-02 212811](https://user-images.githubusercontent.com/21228689/205380157-4c5b8336-b3ab-4f6d-ad61-c405f671ec04.png)
> 
> per facilitare l'operazione di backup, tutte le "parti critiche" hanno nella parte finale un pulsante per scaricare (blu) e per caricare (verde) le proprie configurazioni

![image](https://user-images.githubusercontent.com/82624098/205381068-0712dfdf-b3df-4d78-95a3-6cd5efd5cd76.png)
questo invece che errore è?
