### ISSUE TITLE
WARNING: Il server StreamSB non è supportato.

### ISSUE THREAD

**Issue by MainKronos** [MainKronos/Sonarr-AnimeDownloader#88]
![image](https://user-images.githubusercontent.com/82624098/205381068-0712dfdf-b3df-4d78-95a3-6cd5efd5cd76.png)

- **Nome Anime**: Lucifer and the Biscuit Hammer
- **Link di AnimeWorld**: https://www.animeworld.tv/play/hoshi-no-samidare.Sc-m0
- 
- **Nome Anime**: Raven of the Inner Palace
- **Link di AnimeWorld**: https://www.animeworld.tv/play/koukyuu-no-karasu.9c6ln/AriRcf

_Originally posted by @ManuJapan89 in https://github.com/MainKronos/Sonarr-AnimeDownloader/issues/87#issuecomment-1335815917_

**Comment by MainKronos** [comment]
è un errore che non dovrebbe accadere, probabilmente hanno fatto qualche modifica al sito. Da quanto tempo appare?
Accade solo per questo anime?
@ManuJapan89

**Comment by ManuJapan89** [comment]
> è un errore che non dovrebbe accadere, probabilmente hanno fatto qualche modifica al sito. Da quanto tempo appare? Accade solo per questo anime? @ManuJapan89

te l'ho segnalato subito. questo tool per me è un salvavita. lo monitoro spesso. scarico dai 40 ai 60 shows a stagione. quindi è mio interesse avvisarti asap

**Comment by ManuJapan89** [comment]
![image](https://user-images.githubusercontent.com/82624098/205383514-a064ba6d-3aed-4b69-8eeb-2010f65ac2f0.png)
lo fa solo con questa serie attualmente

**Comment by ManuJapan89** [comment]
@MainKronos sai per caso perchè dal docker stesso sulla macchina, mi appare cosi?
![image](https://user-images.githubusercontent.com/82624098/205386520-79fc5a10-7300-439b-8770-feaaebe1c38c.png)

**Comment by ManuJapan89** [comment]
![image](https://user-images.githubusercontent.com/82624098/205454877-68e16664-01b6-42e9-985e-23605bb420bd.png)
adesso me lo fà anche su questa

**Comment by MainKronos** [comment]
Prova la versione [dev](https://github.com/MainKronos/Sonarr-AnimeDownloader/pkgs/container/anime_downloader/49776097?tag=dev) e dimmi se il problema e stato risolto.
