### ISSUE TITLE
il programma non scarica più anche se SOLO 1 collegamento è inesistente

### ISSUE THREAD

**Issue by ManuJapan89** [MainKronos/Sonarr-AnimeDownloader#89]
Ciao, ho notato una cosa
SE una pagina lato animeworld viene modificata e/o cambiata e il puntamento che tu hai messo nella tabella di conversione non è valido
si verifica questo errore
![image](https://user-images.githubusercontent.com/82624098/208240306-fc4436b9-90cc-4b5b-946b-88f128b98c6c.png)
quando succede,anche se altri episodi sono usciti di altri anime e hanno collegamenti validi, nulla viene scaricato e si và in loop ogni 30 minuti con questo errore.
Si può fare in modo che questo errore venga posto SI in risalto perchè è da fixare ma che il programma continui a scaricare il resto?
perchè basta che gli amici di animeworld cambiano mezzo carattere in un link di un anime e per giorni l'automatismo non lavora 

Spero di aver spiegato correttamente cosa intendo :)

**Comment by MainKronos** [comment]
Prova la versione [dev](https://github.com/MainKronos/Sonarr-AnimeDownloader/pkgs/container/anime_downloader/59372688?tag=dev), dovrebbe risolvere il problema
