### ISSUE TITLE
[Domanda] Doppie Librerie su plex + Bug / Miss-Configurazione?

### ISSUE THREAD

**Issue by zFerry98** [MainKronos/Sonarr-AnimeDownloader#9]
Salve, vorrei capire come va configurato in una situazione dove su plex ho due librerie gestite da Sonarr.
Es:
Libreria 1 > Anime
Libreria 2 > Anime da revisionare

Lib1 = H:\Anime2\
Lib2 = H:\FanSeries\

Cosa dovrei fare per far si che per esempio, The Promised Neverland s02 venga scaricato in Anime2 mentre un Black Clover in FanSeries?

Inoltre non so il perché ma ho già provato con la v. 1.1.0 ad aggiungere due serie (ho configurato 1 sola cartella, quella principale) ma non vengono scaricate (One Piece S21 e The Promised NeverLand s02)... anzi, non vengono proprio considerate. Poi nel log vengono "considerate" serie che non ho mai aggiunto al json (web).

<details>
 <summary>Img esempio:</summary>

![image](https://user-images.githubusercontent.com/17975351/107122613-00583d80-6899-11eb-9f6a-bd9a268afb38.png)
Json: 
![image](https://user-images.githubusercontent.com/17975351/107122692-7ceb1c00-6899-11eb-8fed-0d57a2efac47.png)

Config:
![image](https://user-images.githubusercontent.com/17975351/107122725-b91e7c80-6899-11eb-8018-b4e9225fe506.png)

</details>

OS: WS2019 x64 DataCenter;
Sonarr per windows installato NON su Docker;
Docker Desktop (quello nuovo) ma con HyperV (niente WSL2 perché WS2019 che uso non è ancora aggiornato per il supporto) e niente "trucco" WSL1.

Ora provo a reinstallare la nuova versione 1.1.1 e vedo se cambia qualcosa.

### EDIT:
Ecco, sarebbe utile spiegare per bene cosa c'è da configurare su Sonarr per le serie che devono essere gestite da questo programma. Tipo togliere il monitor status? Metterlo? Mettere un tag particolare per la serie?

### EDIT2: 
![image](https://user-images.githubusercontent.com/17975351/107123410-b45bc780-689d-11eb-8f0c-02602a658504.png)

Primo avvio dopo aver reinstallo da 0 la docker (lasciando però lo stesso json)

**Comment by MainKronos** [comment]
Hai ragione, effettivamente è poco chiaro.
Non ho ben capito se sei riuscito a risolvero da solo😅, ma comunque...

# Problema cartelle

Per fare ciò che stai chiedendo è necessario avere l'ultima versione `1.1.1` perchè quelle precedenti usano una variabile ambientale `ANIME_PATH` che limita questo funzionamento.
Per settare la cartella di destinazione bisogna modificare la configurazione della serie da sonarr (Perchè è da li che il programma prende tutte le informazioni)
![Inkedserie_LI](https://user-images.githubusercontent.com/21228689/107131506-5e0b7a80-68d7-11eb-9a5e-d77afbbe0013.jpg)
Ad esempio nella mia configurazione la serie è archiviata in `/tv/Anime/The Promised Neverland`, se volessi far andare gli episodi di questa serie in un'altra cartella dovrei modificare questo settaggio, per esempio in questo: `/tv/Anime2/The Promised Neverland`, in questo caso tutti gli episodi scaricati andranno in questa nuova directory.
Il problema più complicato è che stai utilizzando Sonarr non in Docker mi sarebbe di aiuto se mi alleghi la configurazione che hai usato per il Container `Sonarr-AnimeDownloader` per quanto riguarda i volumi.

# Problema serie

Per quanto riguarda le serie... Il programma cerca di scaricare solo gli episodi mancanti, quindi per escludere degli episodi (BLU) oppure completamente una stagione (VERDE) o una serie (ROSSO) bisogna rimuovere il monitor status.
![status](https://user-images.githubusercontent.com/21228689/107131722-3c12f780-68d9-11eb-8e1a-3a00f3af995a.png)


Spero di esserti stato almeno un pochino utile 😅, se c'è qualcosa a cui non ho risposto o non sono stato abbastanzo chiaro scivi pure👍

**Comment by zFerry98** [comment]
> Ad esempio nella mia configurazione la serie è archiviata in /tv/Anime/The Promised Neverland, se volessi far andare gli episodi di questa serie in un'altra cartella dovrei modificare questo settaggio, per esempio in questo: /tv/Anime2/The Promised Neverland, in questo caso tutti gli episodi scaricati andranno in questa nuova directory.

Allora al programma serve la directory (nel mio caso) "`H:\`"
Che contiene sia Anime2 che FanSeries... Questo però è un problema per due motivi:

1) Se la seconda cartella si trova in "`E:\`" ? Essendo in "`E:\`" la seconda cartella e non potendo avere due mount con "`/tv`" come fa il programma a trovare la seconda mount?
2) Correlato al primo punto; A cosa serve quindi la Mount "`/tv`" se da quel che dici, il programma, usa le directory da Sonarr?

Presumo serva per la limitazione di Docker a non poter accedere direttamente alle unità connesse al pc... Rimane comunque il problema che se ho una libreria gestita da Sonarr da più cartelle sparse per i vari HDD nel pc... non so come far vedere tutte quelle unità riunite sotto la mount "`/tv`"
<details>
 <summary>(</summary>

che possiamo definire come se fosse la root directory, per il programma, per le serie. 
`/` questa in linux, 
dove se:
/tv = `/`
Lib1 = `H:\Anime2\`
Lib2 = `H:\FanSeries\`
Lib3 = `E:\Anime3\`

Otteniamo ipoteticamente:
`/Lib1/`
`/Lib2/`
`/Lib3/`

Mentre nel lato pratico (cioè ora):
`-v H:\Anime2:/tv`
`-v E:\Anime3:/tv`
**NON** si può fare e quindi rimane solo una delle due.

Posso mettere
`-v H:\Anime2:/tv`
`-v H:\FanSeries:/tv2`
`-v E:\Anime3:/tv3`
ma non risolvo nulla perché il programma ha come sola e unica mount da usare per le scan di episodi la path `/tv` e **NON** `/tv2` e `/tv3` "inventate" da me come workarround per inserire le mount anche di queste due directory nella docker
Spero di essermi spiegato bene.
In poche parole, facendo `CD /tv` dalla CLI di Docker, quello che vedo è il percorso della mount `-V H:\FanSeries:/tv` invece che:
> Otteniamo ipoteticamente:
`/Lib1/`
`/Lib2/`
`/Lib3/`

)
</details>.

## SONARR
>Per quanto riguarda le serie... Il programma cerca di scaricare solo gli episodi mancanti, quindi per escludere degli episodi (BLU) oppure completamente una stagione (VERDE) o una serie (ROSSO) bisogna rimuovere il monitor status.

Anche qui ci sono dei problemi...
Il primo è che Sonarr non è li a caso, infatti quelle serie rosse e blu (Rosse mancano degli episodi e sono monitorate; Blu Sono serie che non sono ancora terminate) vengono tutt'ora gestite e scaricate automaticamente da Sonarr appena escono i torrent degli episodi. Quindi quel Fruit Basket 2019 e Assault Lily non posso mica togliere il monitor e far smettere di scaricare gli episodi (a quel punto non avrebbe senso sonarr in primis). Perciò la domanda è spontanea...
Questo programma in realtà è pensato più che altro per sostituire il Download Client di Sonarr (a torrent) con un Download Client a DDL sulla libreria di AnimeWorld?
Indipendentemente dalla risposta, per ora, la soluzione che vedo io è di mettere un Tag specifico alle serie che voglio far scaricare SOLO da questo Programma, Es, `DockerAnimeWorld`, il quale leggendo tale tag, capisce che quella è una serie che deve cercare gli episodi e aggiungerli se mancanti.

> Non ho ben capito se sei riuscito a risolverlo da solo😅, ma comunque...

No! Continua a darmi errore che non trova le due serie in rosso (per sonarr) nono stante facendo `CD /tv` e poi `ls` questo sia il contenuto (giusto direi):
![image](https://user-images.githubusercontent.com/17975351/107146306-8763ef00-6947-11eb-89d7-5dc733c78407.png)

**Comment by MainKronos** [comment]
Il problema dei log è che le informazioni che Sonarr invia al programma sono divise in 'pagine' e vista la mia pigrizia l'ho strutturato in modo tale che analizzasse solo la prima pagina di informazioni con ordine per le serie con uscita dal più vecchio al più recente. Quindi è per questo che vedi sempre il solito Log... Con la prossima versione farò in modo che il programma riesca ad analizzare tutte le informazioni, nel mentre (come soluzione provissoria) deseleziona momentaneamente il monitoraggio per le serie che non ti interessano 😅

# Problema cartelle
Per il problema delle cartelle (mi rendo conto che non è praticamente spiegato 😅)....
Le mount puoi farne quanti ne vuoi, non c'è una limitazione...
E per la mount `/tv` non è obbligatorio che si chiami `/tv`, può chiamarsi come ti pare

adesso il problema è che se fossimo su linux ti dire che ad esempio:
- hai che parte gli anime si trovano su `/myfolder/myanime`
- l'altra parte degli anime si trovano su `/myfolder2/myanimeOther`
la soluzione sarebbe di fare così:
```
-v /myfolder/myanime:/myfolder/myanime
-v /myfolder2/myanimeOther:/myfolder2/myanimeOther
```

ma su windows..... BO😂

**Comment by MainKronos** [comment]
Per l'ultimo problema....
Probabilmente gli anime li stà spostando nella cartella indicata da sonarr....
Per trovarli (😅) segui le directory indicate nelle impostazioni della serie su Sonarr all'interno del Container

Probailmente ti ha creto delle cartelle 😅
Perchè per risolvere un'altro problema che mi avevano fatto notare, ho dovuto mettere che se non ci fossero state le cartelle corrispondenti indicate da Sonarr, il programma avrebbe dovuto crearle

**Comment by zFerry98** [comment]
## SOFTWARE:
> nel mentre (come soluzione provissoria) deseleziona momentaneamente il monitoraggio per le serie che non ti interessano 😅

Non posso, se domani GruppoX rilascia un episodio di quella serie non mi viene scaricato... A questo punto tolgo sonarr e vado su RAD a vedermi eps appena escono.
È un problema ma basta farsi che vengano ignorate dal log o ignorate proprio dal programma. Nulla di più.


>## Problema cartelle
>Per il problema delle cartelle (mi rendo conto che non è praticamente spiegato 😅)....
>Le mount puoi farne quanti ne vuoi, non c'è una limitazione...
>E per la mount `/tv` non è obbligatorio che si chiami `/tv`, può chiamarsi come ti pare
>
>adesso il problema è che se fossimo su linux ti dire che ad esempio:
>
>hai che parte gli anime si trovano su `/myfolder/myanime`
>l'altra parte degli anime si trovano su `/myfolder2/myanimeOther`
>la soluzione sarebbe di fare così:
>```
>-v /myfolder/myanime:/myfolder/myanime
>-v /myfolder2/myanimeOther:/myfolder2/myanimeOther
>```
>ma su windows..... BO😂

...Allora non capisco proprio come funziona la ricerca del programma... Mi pareva di aver intuito che fosse hardcoded la mount `/tv` con relativo percorso UNICO associato (quindi un solo percorso che deve contenere tutte le cartelle anime o una sola).
Per questo anche facendo una mount `-v E:\CartellaAcaso1\:/NomeACasoCheVoglioIO` pensavo fosse inutile in quanto il programma faceva partire le scan in `/tv` e basta (almeno così si intuiva dalla "documentazione").
Se però mi dici che qualsiasi sia la mount (`-v qualsiasicosa:/qualsiasicosa`) lui in qualche modo trova le cartelle... Allora 👍. Ti dirò tra poco che ri faccio per la 4 volta la docker con le nuove settings.
Per sicurezza farò così:
```
-v H:\Anime2\:/Anime2
-v H:\FanSeries\:/FanSeries
-v E:\Anime3\:/Anime3
```
Teniamo conto che per Sonarr la root directory delle serie è il percorso intero (che per te è /tv su docker).
![image](https://user-images.githubusercontent.com/17975351/107150637-0a447400-695f-11eb-91a5-b7cba3b40d5e.png)

----------------------------------------------------------------------------------------------------------------------------------------------
## EPISODI:
> Per l'ultimo problema....
>Probabilmente gli anime li stà spostando nella cartella indicata da sonarr....
>Per trovarli (😅) segui le directory indicate nelle impostazioni della serie su Sonarr all'interno del Container
>
>Probailmente ti ha creto delle cartelle 😅
>Perchè per risolvere un'altro problema che mi avevano fatto notare, ho dovuto mettere che, se non ci fossero state le cartelle >corrispondenti indicate da Sonarr, il programma avrebbe dovuto crearle

Come precedentemente mandato tramite screen, ho seguito le cartelle sia dalla CLI (finestra nera in alto a SX) sia da Esplora File di Windows Subito sotto. Non ci sono da nessuna parte. Secondo il LOG i file sono stati spostati in "`H:\FanSeries\Saint Seiya`" ... tecnicamente dovrebbero essere nella cartella principale (nemmeno nella sotto cartella "Stagione 05" che Sonarr dovrebbe creare e usare per gli episodi di quella stagione). L'unico dubbio che mi viene... è che abbia creato la cartella `H` in `/` quindi "`/H/FanSeries/Saint Seiya/`" per linux DENTRO la docker (invece che usare la cartella nella mount... motivo per la quale davo per scontato che `/tv` era hardcoded). 
Ma dire di no visto che proprio non mi da nessuna Directory con `LS` su `MNT` e su `/`: 
![image](https://user-images.githubusercontent.com/17975351/107151038-db2f0200-6960-11eb-89dd-ab9313a27e9d.png)

**Comment by MainKronos** [comment]
Il nome del file dovrebbe essere così: `{SonarrTitle} - S{Stagione}E{Episodio}`
es: `Saint Seiya - S1E2.mp4`

Per quanto riguarda lo spostamento dei file, farò dei test poi ti informo😅

**Comment by MainKronos** [comment]
Per l'ultimo problema che hai scritto...
Stà riscaricando gli episodi semplicemente perchè non li ha spostati correttament, quindi sonarr non li vede e crede che manchino

**Comment by zFerry98** [comment]
> Il nome del file dovrebbe essere così: `{SonarrTitle} - S{Stagione}E{Episodio}.{ext}`
> es: `Saint Seiya - S1E2.mp4`
> 
> Per quanto riguarda lo spostamento dei file, farò dei test poi ti informo😅

![image](https://user-images.githubusercontent.com/17975351/107152235-0b799f00-6967-11eb-94a8-23898f9cd0d5.png)
Sulla CLI docker non trova niente nonostante stia scaricando ora ep 8 della s05...
LOL

**Comment by zFerry98** [comment]
> Per quanto riguarda le modifiche al database, funziona anche a caldo, non c'è bisogno che riavvii il container👍

Le aggiunte sì, il fatto che subito dopo aver aggiunto voglio anche che inizi subito il download (se fermo) no.
Dovrei aspettare la routine / task di xMinuti / xOre che fa partire la scan.

**Comment by MainKronos** [comment]
Si, effettivamente dovresti aspettare la prossima scan....
Le scan vengono fatte ogni 30 minuti

**Comment by MainKronos** [comment]
HAHAHAAH, ho scoperto dove te le sposta!
Credo..... che siano in una cartella che ha come nome la directory e si trova in `/script`...
Appena puoi controlla e dimmi se è quella

**Comment by zFerry98** [comment]
![image](https://user-images.githubusercontent.com/17975351/107154332-bba0d500-6972-11eb-8c15-9d51f0d09e5c.png)
LOL 🤣 neanche ho pensato di fare `LS` subito aperta la CLI.

Rimane comunque un problema o meglio, nuovo problema.
Nanatsu non viene considerato (riscarica in loop saint seiya ma non passa a nanatsu)

**Comment by MainKronos** [comment]
ok, prova ad usare la nuova versione `1.2.0`

**Comment by zFerry98** [comment]
> ok, prova ad usare la nuova versione `1.2.0`
> E poi dimme se ho risolto almeno qualcosa 😂

![image](https://user-images.githubusercontent.com/17975351/107162239-1aca0e00-69a2-11eb-9232-74dad74e4194.png)
Direi di sì.. tranne che non vengono smistati nelle sotto stagioni (ma è già qualcosa). Ora devo aspetto che finisca SS e vediamo se prende Nanatsu o salta come prima

**Comment by MainKronos** [comment]
Il problema che gli episodi non vengono messi dentro le cartelle delle stagioni è un problma molto vecchio...
La funzione `def RenameSerie(seriesId)` non funziona come dovrebbe e ancora non sono riuscito a capirne il motivo

**Comment by zFerry98** [comment]
> Il problema che gli episodi non vengono messi dentro le cartelle delle stagioni è un problma molto vecchio...
> La funzione `def RenameSerie(seriesId)` non funziona come dovrebbe e ancora non sono riuscito a capirne il motivo

Ok funziona tutto.
Ma fargli creare la cartella "Stagione xx" dove xx viene sostituito dal numero di stagione sul JSON / Episodio scaricato?
Comunque vedo sta settimana come si comporta e aggiornerò in caso di novità o bugs 👍.
Per ora mi ritengo soddisfatto che possa scaricare le serie non su torrent.
Grazie per il supporto.
