### ISSUE TITLE
Scelta stagione da scaricare

### ISSUE THREAD

**Issue by devaleriofrancesco** [MainKronos/Sonarr-AnimeDownloader#93]
Ciao,

grazie anzitutto per questo fantastico software😍.

Volevo sapere se ci fosse la possibilità di scegliere la stagione da scaricare quando su Sonarr la numerazione episodi è assoluta mentre su Animeworld è divisa in stagioni.

Faccio l'esempio con SPY x FAMILY.

Su Sonarr abbiamo la stagione 1 completa mentre su Animeworld abbiamo la 1 e la 2 parte.

Mettiamo caso che io ho già visto la prima parte ( i primi 13 episodi) e non voglio scaricarli. Vorrei scaricare solo la seconda parte.

C'è già la possibilità di fare ciò che descrivo?

Grazie mille

**Comment by MainKronos** [comment]
Questo dovrebbe risolvere il tuo problema
https://github.com/MainKronos/Sonarr-AnimeDownloader/blob/main/FAQ.md#una-stagione-di-sonarr-%C3%A8-composta-da-due-stagioni-di-animeworld

**Comment by devaleriofrancesco** [comment]
Non proprio...

Nel senso, la mia necessità è scaricare solamente la parte 2 di Spy x family, ma se inserisco su anime downloader solo il link alla parte 2 e lascio scaricare il primo episodio della parte 2, su sonarr mi indica che ho scaricato l'episodio 1 della parte 1.

Se necessario allego table.json è un po' di screen

Grazie

**Comment by MainKronos** [comment]
Per scaricare solo la seconda parte devi fare così:
1) Innanzitutto devi configurare correttamente la tabella di conversione
1.1) Creare la serie SpyxFamaly come fai normalmente, selezionando la stagione 1 e aggiungendo il link di animeworld **della prima parte**.
1.2) Dopodiché aggiungi il link della **seconda parte** con l'apposito pulsante.
![add](https://user-images.githubusercontent.com/21228689/219936087-b98d8b75-2e5b-4881-bcd7-705b410b40a2.png)
1.3) Dovresti alla fine avere questo risultato: 
![link](https://user-images.githubusercontent.com/21228689/219936111-f9e26322-6716-4f32-b9a8-d6f424a4ec55.png)
2) Per scaricare solo gli episodi della seconda parte bisogna andare su Sonarr e selezionarli
![select](https://user-images.githubusercontent.com/21228689/219937446-02e01110-9a32-4f3b-a46a-2d5847f401a6.png)
> **Note** 
> Per ricordarti come configurare correttamente il programma in questi casi basta pensare che, il numero subito sotto il titolo dell'anime si riferisce alla stagione di Sonarr e i link sotto si riferiscono a dove si trovano gli episodi relativi a quella stagione. In questo caso gli episodi sono divisi in due link, quindi il programma analizza il primo link e il secondo link come se fossero un unica cosa; ad esempio di SpyxFamaly, la prima parte finisce al 12-esimo episodio e mettiamo che vogliamo scaricare l'episodio 15, allora il programma procede in questo modo: scorre tutti gli episodi del primo link alla ricerca di un episodio che abbia come numero uguale a 15, se non lo trova allora passa al secondo link, prende il numero dell'episodio, ci somma 12 (valore dell'ultimo episodio del link precedente) e controlla se questo valore è uguale a 15, se cosí fosse lo scarica e si ferma.

Spero di aver risolto il tuo problema, in caso di dubbi scrivi pure

**Comment by devaleriofrancesco** [comment]
Funziona! Sei stato gentilissimo, grazie mille❤
