### ISSUE TITLE
[BUG] import error in python 3.9

### ISSUE THREAD

**Issue by r0bb10** [MainKronos/Sonarr-AnimeDownloader#96]
### Livello di Errore:
- `🅴🆁🆁🅾🆁`

### Messaggio di Errore

```-------------------------------------
GID/UID
-------------------------------------
User uid:	1000
User gid:	1000
-------------------------------------
Traceback (most recent call last):
  File "/script/main.py", line 14, in <module>
    from job import job
  File "/script/job.py", line 5, in <module>
    import animeworld as aw
  File "/usr/local/lib/python3.9/site-packages/animeworld/__init__.py", line 4, in <module>
    from .utility import find
  File "/usr/local/lib/python3.9/site-packages/animeworld/utility.py", line 158, in <module>
    SES = MySession() # sessione contenente Cookie e headers
  File "/usr/local/lib/python3.9/site-packages/animeworld/utility.py", line 23, in __init__
    self.fixCookie()
  File "/usr/local/lib/python3.9/site-packages/animeworld/utility.py", line 43, in fixCookie
    raise DeprecatedLibrary(frame.filename, frame.function, frame.lineno)
animeworld.exceptions.DeprecatedLibrary: Il sito è cambiato, di conseguenza la libreria è DEPRECATA. -> [File /usr/local/lib/python3.9/site-packages/animeworld/utility.py in fixCookie - 42]
```

### Descrizione [_Opzionale_]
Da oggi senza aver cambiato assolutamente nulla il container non si avvia per questo errore, oltretutto lo stack (uso portainer con docker-compose) non passa neanche gli enviroment (tipo uso uid 1026 ma nel log mostra 1000).
Non so a cosa può esser legato, anche resettando i config non cambia, non si avvia.. è un problema solo mio?

**Comment by MainKronos** [comment]
Questo non è un problema causato da te. L'eccezione `DeprecatedLibrary` viene sollevata quando vengono apportate delle modifiche importanti al sito di animeworld, tali per cui la libreria non riesce piú a mappare la pagina.

Questo problema rende completamente inutilizzabile il programma. Mi metto subito a lavoro per risolvere il problema quanto prima.

Da quel che vedo nel log il problema dovrebbe essere nella funzione [`fixCookie`](https://github.com/MainKronos/AnimeWorld-API/blob/master/animeworld/utility.py#L29)

**Comment by MainKronos** [comment]
Problemi risolti con la nuova versione [`1.9.3`](https://github.com/MainKronos/Sonarr-AnimeDownloader/releases/tag/1.9.3)

**Comment by r0bb10** [comment]
Confermo, 1.9.3 funzionante, grande lavoro come sempre!
