### ISSUE TITLE
[BUG] error from daemon in stream error grabbing logs

### ISSUE THREAD

**Issue by ManuJapan89** [MainKronos/Sonarr-AnimeDownloader#99]
Ciao, da pagina web i log si vedono
ma da docker ho questo errore

![image](https://user-images.githubusercontent.com/82624098/235366442-e36f5351-525f-422b-99f1-615f779dfb17.png)
[log.log](https://github.com/MainKronos/Sonarr-AnimeDownloader/files/11361863/log.log)

allego sia screen che log

**Comment by MainKronos** [comment]
forse si è corrotto il file di log del container (`/var/lib/docker/containers/*/*-json.log`)
Prova a ricreare il container

**Comment by ManuJapan89** [comment]
ricreandolo mi pare si sia fixato
thanks :)
